### PR TITLE
fix: check function's instance class is a subclass of virtual method

### LINKED ISSUE #1971: class extends basis class with generic compile error
Hello, 
Is this compile error reasonable? I'm not sure whether assemblyscript supports the way of following inheritance.

ERROR TS2322: Type '(this: assembly/index/B<f64,~lib/string/String>, f64) => void' is not assignable to type '(this: assembly/index/A<i32>, i32) => void'.

     foo(a:T):void{

```
class A<T>{
    foo(a:T):void{
        trace(`class A ${a}`)
    }
}
class B<T,V> extends A<T>{
    foo(a:T):void{
        trace(`class B ${a}`)
    }
}
export function test_foo():void{
    let v = new B<i32,f64>()
    let v2 = new B<i32,string>()
    let v3 = new B<f64,string>() // if comment this line, compile OK
    const v_usize = changetype<usize>(v)
    changetype<A<i32>>(v_usize).foo(1)
}
```

### PR DESCRIPTION
**Pull request by willemneal**
fixes #1971

Generic base classes have an issue where all instances regardless of generic are collected as instances of its virtual methods.  This checks to make sure that only methods from classes that extend the generic base class are added to the virtual table.

### CODE REVIEW

File: tests/compiler/class-overloading-cast.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+}
+class B<T, V> extends A<T> {
+  foo(a: T): void {
+    trace(`class B ${a}`);
+  }
+}
+export function test_foo(): void {
+  let v = new B<i32, f64>();
+  // let v2 = new B<i32,string>();
+  let v3 = new B<f64, string>(); // if comment this line, compile OK
```
Comment (MaxGraey) [inline tests/compiler/class-overloading-cast.ts:14]: Why these comments present here?

File: tests/compiler/class-overloading-cast.ts [hunk 2]
```diff
@@ -0,0 +1,16 @@
+class A<T> {
+  foo(a: T): void {
+    trace(`class A ${a}`);
+  }
```
Comment (MaxGraey) [inline tests/compiler/class-overloading-cast.ts:4]: How about return string?
```ts
foo(a: T): string {
    return "A";
}
```
and same for `B#foo` but return `"B"`.
And later call this functions with and compare with expected values with assert

File: src/compiler.ts [hunk 3]
```diff
@@ -6992,6 +6992,8 @@ export class Compiler extends DiagnosticEmitter {
       if (classInstances) {
         for (let _values = Map_values(classInstances), j = 0, l = _values.length; j < l; ++j) {
           let classInstance = _values[j];
+          // Chcek if the parent class is a subtype of instance's class
+          if (!classInstance.isAssignableTo(<Class>instance.parent)) continue;
```
Comment (dcodeIO) [inline src/compiler.ts:6996]: The cast here can be moved up to the beginning of the function so we don't need to property-access-and-cast each time in the loop :)

Comment (dcodeIO) [reply src/compiler.ts:6996]: Also should add an assert before the cast to make sure. We are typically doing that in other places where we rely on `kind` to have a particular value.

Comment (willemneal) [reply src/compiler.ts:6996]: Not sure where I would put it since I need access to the current `_values[j]`.

File: tests/compiler/class-overloading-cast.ts [hunk 4]
```diff
@@ -0,0 +1,24 @@
...
+class B<T, V> extends A<T> {
+  foo(a: T): string {
+    return "B";
+  }
+}
+
+class C extends A<string>{}
+
+let v = new B<i32, f64>();
+let v2 = new B<i32,string>();
```
Comment (MaxGraey) [inline tests/compiler/class-overloading-cast.ts:15]:
```suggestion
let v2 = new B<i32, string>();
```

File: src/compiler.ts (hunk 3 above)
Comment (dcodeIO) [reply src/compiler.ts:6996]: `instance` is passed into the function as an argument, so that can be moved up:

```ts
var parent = instance.parent;
assert(parent.kind == ElementKind.CLASS);
var parentClassInstance = <Class>parent;
```

To then here become:

```ts
if (!classInstance.isAssignableTo(parentClassInstance ) continue;
```

Comment (willemneal) [reply src/compiler.ts:6996]: Ah got it.

**Comment by willemneal** [comment]
@dcodeIO @MaxGraey 

Anything else needed for this?

File: src/compiler.ts [hunk 5]
```diff
@@ -6992,6 +6994,8 @@ export class Compiler extends DiagnosticEmitter {
       if (classInstances) {
         for (let _values = Map_values(classInstances), j = 0, l = _values.length; j < l; ++j) {
           let classInstance = _values[j];
+          // Chcek if the parent class is a subtype of instance's class
+          if (!classInstance.isAssignableTo(parentClassInstance)) continue;
```
Comment (dcodeIO) [inline src/compiler.ts:6998]: More an intuition right now, but could you elaborate why this is the right check?

Comment (willemneal) [reply src/compiler.ts:6998]: Well assuming `isAssingableTo` works as `isSubClassOf`, then consider:

```ts
class A<T> {
  foo(t: T): string { return "A";}
  }
  
class B extends A<i32>{
 foo(t: i32): string { return "B";}
}

class C extends A<string>{
 foo(t: string): string { return t; }
 }

let a: A<i32> = new B();
let a: A<string> = new C();
```

Currently given the way that virtual methods are collected, the instance of `A<i32>`'s `foo` method would have both `B` and `C` in the `classInstances` above. So this check is when generating the virtual table for `A<i32>`s `foo` method, only subclasses of `A<i32>` should be considered.

**Comment by willemneal** [comment]
@MaxGraey Thoughts?

File: src/compiler.ts (hunk 5 above)
Comment (willemneal) [reply src/compiler.ts:6998]: @dcodeIO @MaxGraey

Comment (MaxGraey) [reply src/compiler.ts:6998]: If @dcodeIO confirms this PR as correct, we'll be merge it all soon with some PRs marked as "feat"

Comment (dcodeIO) [reply src/compiler.ts:6998]: I *think* this looks correct to me. I do not think that we'll have to make it a breaking 0.20, though :)

**Review by dcodeIO — APPROVED** [review]

**Review by MaxGraey — APPROVED** [review]

**Comment by willemneal** [comment]
@MaxGraey Are we waiting to release this with a major bump?  It should be a patch and could be merged now.

**Comment by willemneal** [comment]
@MaxGraey, this is bug is a blocker for me.

**Comment by MaxGraey** [comment]
Thanks!
