### PR TITLE
fix: Update binaryen's constants

### LINKED ISSUE #1551: Potentially wrong SIMD opcode generation in 0.17.2
Hi all, I'm not sure if that's related to the recent Binaryen updates in 0.17.2, but the following code (which compiles just fine w/ all recent assemblyscript versions < 0.17.2) is now causing a validation error during compile and seemingly produces the wrong SIMD opcodes to begin with:

https://github.com/thi-ng/umbrella/blob/develop/packages/simd/assembly/abs.ts#L12

```ts
export function abs4_f32(
    out: usize,
    a: usize,
    num: usize,
    so: usize,
    sa: usize
): usize {
    so <<= 2;
    sa <<= 2;
    const res = out;
    for (; num-- > 0; ) {
        v128.store(out, f32x4.abs(v128.load(a)));
        out += so;
        a += sa;
    }
    return res;
}
```

```text
[wasm-validator error in function assembly/abs/abs4_f32] i32 != v128: store value type must match, on 
[none] (v128.store
 [i32] (local.get $0)
 [i32] (i64x2.all_true
  [v128] (v128.load
   [i32] (local.get $1)
  )
 )
)
FAILURE validate error
    at Object.main (/Users/thing/umbrella/node_modules/assemblyscript/cli/asc.js:735:23)
    at /Users/thing/umbrella/node_modules/assemblyscript/bin/asc:21:47
```

Where is that `i64x2.all_true` op coming from here? Should be `f32x4.abs`...

### PR DESCRIPTION
**Pull request by MaxGraey**
Fix #1551

### CODE REVIEW

File: src/module.ts [hunk 1]
```diff
@@ -97,20 +97,21 @@ export enum ExpressionId {
...
-  RefNull = 40 /* _BinaryenRefNullId */,
-  RefIsNull = 41 /* _BinaryenRefIsNullId */,
-  RefFunc = 42 /* _BinaryenRefFuncId */,
-  Try = 44 /* _BinaryenTryId */,
-  Throw = 45 /* _BinaryenThrowId */,
-  Rethrow = 46 /* _BinaryenRethrowId */,
-  BrOnExn = 47 /* _BinaryenBrOnExnId */,
-  TupleMake = 48 /* _BinaryenTupleMakeId */,
-  TupleExtract = 49 /* _BinaryenTupleExtractId */
+  MemoryInit = 36 /* _BinaryenMemoryInitId */,
```
Comment (dcodeIO) [inline src/module.ts:100]: Which one is missing here?

File: src/module.ts [hunk 2]
```diff
@@ -193,48 +194,48 @@ export enum UnaryOp {
...
-  BitmaskI32x4 = 81 /* _BinaryenBitmaskVecI32x4 */,
-  NegI64x2 = 82 /* _BinaryenNegVecI64x2 */,
-  AnyTrueI64x2 = 83 /* _BinaryenAnyTrueVecI64x2 */,
-  AllTrueI64x2 = 84 /* _BinaryenAllTrueVecI64x2 */,
-  AbsF32x4 = 85 /* _BinaryenAbsVecF32x4 */,
-  NegF32x4 = 86 /* _BinaryenNegVecF32x4 */,
-  SqrtF32x4 = 87 /* _BinaryenSqrtVecF32x4 */,
-  CeilF32x4 = 88 /* _BinaryenCeilVecF32x4 */,
-  FloorF32x4 = 89 /* _BinaryenFloorVecF32x4 */,
+  NegI16x8 = 74 /* _BinaryenNegVecI16x8 */,
```
Comment (dcodeIO) [inline src/module.ts:197]: Another one missing here

File: src/module.ts [hunk 3]
```diff
@@ -193,48 +194,48 @@ export enum UnaryOp {
...
-  ConvertU64x2ToF64x2 = 106 /* _BinaryenConvertUVecI64x2ToVecF64x2 */,
-  WidenLowI8x16ToI16x8 = 107 /* _BinaryenWidenLowSVecI8x16ToVecI16x8 */,
-  WidenHighI8x16ToI16x8 = 108 /* _BinaryenWidenHighSVecI8x16ToVecI16x8 */,
-  WidenLowU8x16ToU16x8 = 109 /* _BinaryenWidenLowUVecI8x16ToVecI16x8 */,
-  WidenHighU8x16ToU16x8 = 110 /* _BinaryenWidenHighUVecI8x16ToVecI16x8 */,
-  WidenLowI16x8ToI32x4 = 111 /* _BinaryenWidenLowSVecI16x8ToVecI32x4 */,
-  WidenHighI16x8ToI32x4 = 112 /* _BinaryenWidenHighSVecI16x8ToVecI32x4 */,
-  WidenLowU16x8ToU32x4 = 113 /* _BinaryenWidenLowUVecI16x8ToVecI32x4 */,
-  WidenHighU16x8ToU32x4 = 114 /* _BinaryenWidenHighUVecI16x8ToVecI32x4 */
+  TruncSatF32x4ToI32x4 = 100 /* _BinaryenTruncSatSVecF32x4ToVecI32x4 */,
```
Comment (dcodeIO) [inline src/module.ts:223]: And here

File: src/module.ts [hunk 4]
```diff
@@ -386,38 +387,38 @@ export enum BinaryOp {
...
-  MinF64x2 = 169 /* _BinaryenMinVecF64x2 */,
-  MaxF64x2 = 170 /* _BinaryenMaxVecF64x2 */,
-  PminF64x2 = 171 /* _BinaryenPMinVecF64x2 */,
-  PmaxF64x2 = 172 /* _BinaryenPMaxVecF64x2 */,
-  NarrowI16x8ToI8x16 = 173 /* _BinaryenNarrowSVecI16x8ToVecI8x16 */,
-  NarrowU16x8ToU8x16 = 174 /* _BinaryenNarrowUVecI16x8ToVecI8x16 */,
-  NarrowI32x4ToI16x8 = 175 /* _BinaryenNarrowSVecI32x4ToVecI16x8 */,
-  NarrowU32x4ToU16x8 = 176 /* _BinaryenNarrowUVecI32x4ToVecI16x8 */,
-  SwizzleV8x16 = 177 /* _BinaryenSwizzleVec8x16 */
+  AddI32x4 = 151 /* _BinaryenAddVecI32x4 */,
```
Comment (dcodeIO) [inline src/module.ts:390]: Lot's of...

File: src/module.ts [hunk 5]
```diff
@@ -386,38 +387,38 @@ export enum BinaryOp {
...
+  MulI32x4 = 153 /* _BinaryenMulVecI32x4 */,
+  MinI32x4 = 154 /* _BinaryenMinSVecI32x4 */,
+  MinU32x4 = 155 /* _BinaryenMinUVecI32x4 */,
+  MaxI32x4 = 156 /* _BinaryenMaxSVecI32x4 */,
+  MaxU32x4 = 157 /* _BinaryenMaxUVecI32x4 */,
+  DotI16x8 = 158 /* _BinaryenDotSVecI16x8ToVecI32x4 */,
+  AddI64x2 = 163 /* _BinaryenAddVecI64x2 */,
+  SubI64x2 = 164 /* _BinaryenSubVecI64x2 */,
+
+  AddF32x4 = 170 /* _BinaryenAddVecF32x4 */,
```
Comment (dcodeIO) [inline src/module.ts:401]: ...SIMD it seems

File: src/module.ts (hunk 1 above)
Comment (MaxGraey) [reply src/module.ts:100]: I also noticed about all this gaps. Bust can't find any missed parts. Probably it better investigate more but I'm vote fix this issue asap)

File: src/module.ts (hunk 5 above)
Comment (MaxGraey) [reply src/module.ts:401]: I know some SIMD command added into Binaryen just for collecting feedback and highly experimental. And doesn't expose public API in this reason

File: src/module.ts (hunk 1 above)
Comment (dcodeIO) [reply src/module.ts:100]: The missing one appears to be `SIMDLoadStoreLane`: https://github.com/WebAssembly/binaryen/blob/68294338a1cc7337e808671e75933b1134d18a90/src/wasm.h#L573

File: src/module.ts (hunk 2 above)
Comment (dcodeIO) [reply src/module.ts:197]: This one is strange. Order should be: https://github.com/WebAssembly/binaryen/blob/68294338a1cc7337e808671e75933b1134d18a90/src/wasm.h#L163-L166

```
BitmaskVecI8x16
PopcntVecI8x16 // new
AbsVecI16x8
NegVecI16x8
```

meaning something is off here since the missing one is before AbsVecI16x8, not between AbsVecI16x8 and NegVecI16x8 hmm.

File: src/module.ts (hunk 3 above)
Comment (dcodeIO) [reply src/module.ts:223]: Also strange: https://github.com/WebAssembly/binaryen/blob/68294338a1cc7337e808671e75933b1134d18a90/src/wasm.h#L191-L194

File: src/module.ts (hunk 4 above)
Comment (dcodeIO) [reply src/module.ts:390]: These seem to be: https://github.com/WebAssembly/binaryen/blob/68294338a1cc7337e808671e75933b1134d18a90/src/wasm.h#L396-L400

```
  Q15MulrSatSVecI16x8,
  ExtMulLowSVecI16x8,
  ExtMulHighSVecI16x8,
  ExtMulLowUVecI16x8,
  ExtMulHighUVecI16x8,
```

File: src/module.ts (hunk 5 above)
Comment (dcodeIO) [reply src/module.ts:401]: These are: https://github.com/WebAssembly/binaryen/blob/68294338a1cc7337e808671e75933b1134d18a90/src/wasm.h#L416-L419

```
  ExtMulLowSVecI64x2,
  ExtMulHighSVecI64x2,
  ExtMulLowUVecI64x2,
  ExtMulHighUVecI64x2,
```

Suggesting to at least add comments so one can fix them without counting through all the ids to spot them.

File: src/module.ts (hunk 1 above)
Comment (MaxGraey) [reply src/module.ts:101]: Thanks! Done!

File: src/module.ts (hunk 4 above)
Comment (MaxGraey) [reply src/module.ts:397]: Done

File: src/module.ts (hunk 5 above)
Comment (MaxGraey) [reply src/module.ts:411]: Done

File: src/module.ts (hunk 1 above)
Comment (MaxGraey) [reply src/module.ts:101]: Unfortunately c-api missing `_BinaryenSIMDLoadStoreLaneId`. So for now I comment this line

**Review by dcodeIO — APPROVED** [review]
Thanks, looking good to me with the comments! :)
