### PR TITLE
Fix loader definisions

### LINKED ISSUE #905: Error in loader type definitions
I think there are a couple of errors in Loader type definitions. Specifically, in:

* https://github.com/AssemblyScript/assemblyscript/blob/master/lib/loader/index.d.ts#L57
* https://github.com/AssemblyScript/assemblyscript/blob/master/lib/loader/index.d.ts#L59

The return types should be `BigInt64Array` and `BigUint64Array` (not `BigInt32Array` and `BigUint32Array`).

### PR DESCRIPTION
**Pull request by MaxGraey**
Close #905

### CODE REVIEW

File: lib/loader/index.d.ts [hunk 1]
```diff
@@ -7,9 +7,9 @@ interface ImportsObject extends Record<string, any> {
   env?: {
     memory?: WebAssembly.Memory,
     table?: WebAssembly.Table,
-    abort?: (msg: number, file: number, line: number, column: number) => void,
-    trace?: (msg: number, numArgs?: number, ...args: any[]) => void
-  }
+    abort?(msg: number, file: number, line: number, column: number): void,
+    trace?(msg: number, numArgs?: number, ...args: number[]): void
+  };
```
Comment (dcodeIO) [inline lib/loader/index.d.ts]: Semicolon seems wrong here

Comment (MaxGraey) [reply lib/loader/index.d.ts]: Strange, but ts-lint suggest me write semicolon here.
Also semicolons present [here](https://github.com/AssemblyScript/assemblyscript/blob/bb31c0ee66187d5c1732a24d2cc11ef3fba8453d/lib/loader/index.d.ts#L33) for example. I also think this correct

Comment (MaxGraey) [reply lib/loader/index.d.ts]: Because 
```ts
env?: {
  memory?: WebAssembly.Memory
  ...
};
```
is actually type and could be simplify to:
```ts
{
  env?: object;
}
```
So we need semicolon here

Comment (dcodeIO) [reply lib/loader/index.d.ts]: Oh, right :)

**Comment by dcodeIO** [comment]
Nice, thanks!
