### PR TITLE
fix(compiler): Implement proper left / right cyclic builtin rotation for small integers

### LINKED ISSUE #1492: Rotation shift builtins for small typed integers incorrectly implemented
It seems we have wrong polyfills of `rotr` / `rotl` for small integers like `u16` / `u8`. Here how it compile now:
```ts
function rotL16(a: u16, b: u16): u16 {
  return rotl<u16>(a, b);
}
```
current result:
```wat
(func $rotL16 (param $0 i32) (param $1 i32) (result i32)
  local.get $0
  i32.const 65535
  i32.and
  local.get $1
  i32.rotl
  i32.const 65535
  i32.and
 )
```
what I expected:
```wat
(func $rotL16 (param $0 i32) (param $1 i32) (result i32)
  local.get $0
  local.get $1
  i32.const 15
  i32.and 
  i32.shl 
  local.get $0
  i32.const 0
  local.get $1
  i32.sub 
  i32.const 15
  i32.and 
  i32.shr_u
  i32.or  
  i32.const 65535
  i32.and
)
```
which equivalent to:
```ts
function rotl(a: u16, b: u16): u16 {
  return (a << (b & 15)) | (a >>> (-b & 15));
  // rotr<16>(x, y):
  //   return (x >>> (y & 15)) | (x << (-y & 15));
}
```

### PR DESCRIPTION
**Pull request by MaxGraey**
Fix #1492

- [x] I've read the contributing guidelines

### CODE REVIEW

File: src/builtins.ts [hunk 1]
```diff
@@ -1171,14 +1171,22 @@ function builtin_rotl(ctx: BuiltinContext): ExpressionRef {
...
       case TypeKind.I16:
       case TypeKind.U8:
-      case TypeKind.U16:
-      case TypeKind.BOOL: {
-        return compiler.ensureSmallIntegerWrap(
-          module.binary(BinaryOp.RotlI32, arg0, arg1),
-          type
+      case TypeKind.U16: {
+        // (value << (shift & mask)) | (value >>> ((0 - shift) & mask))
+        let mask   = module.i32(type.size - 1);
```
Comment (dcodeIO) [inline src/builtins.ts:1180]: The mask expression is used twice below, but according Binaryen there is a risk when doing that, because optimizations would modify both places. Suggesting to inline all of `mask`, `shiftL` and `shiftR` into the returned binary as it also indicates that these are one-time uses.

File: src/builtins.ts [hunk 2]
```diff
@@ -1221,14 +1229,22 @@ function builtin_rotr(ctx: BuiltinContext): ExpressionRef {
...
       case TypeKind.I16:
       case TypeKind.U8:
-      case TypeKind.U16:
-      case TypeKind.BOOL: {
-        return compiler.ensureSmallIntegerWrap(
-          module.binary(BinaryOp.RotrI32, arg0, arg1),
-          type
+      case TypeKind.U16: {
+        // (value >>> (shift & mask)) | (value << ((0 - shift) & mask))
+        let mask   = module.i32(type.size - 1);
```
Comment (dcodeIO) [inline src/builtins.ts:1238]: See comment above :)

**Comment by dcodeIO** [comment]
Nice find, and thanks for fixing! :)
