### PR TITLE
fix: when parser error, infinite loop in skipStatement (#1999)

### LINKED ISSUE #1999: Small code makes parser hang
Hi!

If you try to paste this small snipped in the [AS editor](https://www.assemblyscript.org/editor.html), and try to look at the WASM generated, the page becomes unresponsive:
```ts
export function foo() {
  if (idof<Foo>() == idof<Bar>) {
    baz();
  } else {
    `Some string`
  }
}
```

Note that:
* the code is not correct (it is missing the parenthesis to call `idof` in `idof<Bar>`)
* if you remove the string template, from the `else` branch, the issue disappear
* if you fix the `idof` call, the issue disappear

Let me know if you need any additional detail on this.

Thanks!

### PR DESCRIPTION
**Pull request by HerrCai0907**
Fixes #1999, where in ```skipBlock(tn: Tokenizer): void```,  the condition of  ```Token.TEMPLATELITERAL``` is missing and ```tn.next()``` also don't go to the next token. It causes infinite loop.

- [x] I've read the contributing guidelines
- [x] I've added my name and email to the NOTICE file

### CODE REVIEW

File: src/parser.ts [hunk 1]
```diff
@@ -4296,7 +4296,8 @@ export class Parser extends DiagnosticEmitter {
           tn.readIdentifier();
           break;
         }
-        case Token.STRINGLITERAL: {
+        case Token.STRINGLITERAL:
+        case Token.TEMPLATELITERAL: {
```
Comment (MaxGraey) [inline src/parser.ts:4300]: Shouldn't this set `tn.readingTemplateString` to `true`?

cc @dcodeIO

**Comment by MaxGraey** [comment]
Could you add tests for `p${1}`, `${2}n` please?

File: src/parser.ts [hunk 2]
```diff
@@ -4296,10 +4296,22 @@ export class Parser extends DiagnosticEmitter {
           tn.readIdentifier();
           break;
         }
-        case Token.STRINGLITERAL: {
+        case Token.STRINGLITERAL:{
```
Comment (MaxGraey) [inline src/parser.ts:4299]:
```suggestion
        case Token.STRINGLITERAL: {
```

**Comment by HerrCai0907** [comment]
Can this PR be merged? I have add some testcase for it.

**Comment by dcodeIO** [comment]
Thanks :)
