### PR TITLE
fix: fix endless recursion during dts generation

### LINKED ISSUE #2269: Recursive Class | RangeError: Maximum call stack size exceeded
Get an error when trying to set up as class as such

[Reproduction link](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPWluY3JlbWVudGFsJmRlYnVnCmNsYXNzIE5vZGUgew0KICB0eXBlOiBpMzIgPSAwOw0KICBjaGlsZHJlbjogQXJyYXk8Tm9kZT4gPSAgbmV3IEFycmF5PE5vZGU+KDApOw0KfQ0KDQpleHBvcnQgZnVuY3Rpb24gdGVzdCgpOiBOb2RlIHsNCiAgcmV0dXJuIG5ldyBOb2RlKCk7DQp9CiMhaHRtbAo=).

```ts
class Node {
    type: i32 = 0;
    children: Array<Node> = new Array<Node>(0);
}
```

Produces the following error:

```
▌ Whoops, the AssemblyScript compiler has crashed during buildTSD :-(
▌ 
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌ 
▌ RangeError: Maximum call stack size exceeded
▌     at Function.from (<anonymous>)
▌     at globalThis.Map_values (https://cdn.jsdelivr.net/npm/assemblyscript/dist/assemblyscript.js:16:493869)
▌     at Nr.isPlainObject (https://cdn.jsdelivr.net/npm/assemblyscript/dist/assemblyscript.js:263:89)
▌     at Nr.toTypeScriptType (https://cdn.jsdelivr.net/npm/assemblyscript/dist/assemblyscript.js:263:1331)
▌     at Nr.toTypeScriptType (https://cdn.jsdelivr.net/npm/assemblyscript/dist/assemblyscript.js:263:646)
▌     at Nr.makeRecordType (https://cdn.jsdelivr.net/npm/assemblyscript/dist/assemblyscript.js:265:222)
▌     at Nr.toTypeScriptType (https://cdn.jsdelivr.net/npm/assemblyscript/dist/assemblyscript.js:263:1464)
▌     at Nr.toTypeScriptType (https://cdn.jsdelivr.net/npm/assemblyscript/dist/assemblyscript.js:263:646)
▌     at Nr.makeRecordType (https://cdn.jsdelivr.net/npm/assemblyscript/dist/assemblyscript.js:265:222)
▌     at Nr.toTypeScriptType (https://cdn.jsdelivr.net/npm/assemblyscript/dist/assemblyscript.js:263:1464)
```

It works when adding a constructor to `Node`, but I am not able to return the object to JS when using a constructor for `Node`.

### PR DESCRIPTION
**Pull request by HerrCai0907**
Fix #2269

- [x] I've read the contributing guidelines
- [x] I've added my name and email to the NOTICE file

### CODE REVIEW

**Review by MaxGraey — APPROVED** [review]

File: src/bindings/tsd.ts [hunk 1]
```diff
@@ -302,17 +302,21 @@ export class TSDBuilder extends ExportsWalker {
...
             typeName = "__Record" + clazz.id.toString();
             sb.push(typeName);
             sb.push(mode == Mode.EXPORT ? "<never>" : "<undefined>");
-            this.deferredTypings.push(this.makeRecordType(clazz, mode));
           } else {
             typeName = "__Internref" + clazz.id.toString();
             sb.push(typeName);
-            this.deferredTypings.push(this.makeInternrefType(clazz));
           }
           seenObjectTypes.set(clazz, typeName);
```
Comment (MaxGraey) [inline src/bindings/tsd.ts:314]: Another option is moving `seenObjectTypes.set(clazz, typeName)` over `if (this.isPlainObject(clazz)) {...} else {...}`

**Comment by MaxGraey** [comment]
What about this approach?
```ts
let isPlain = this.isPlainObject(clazz);
typeName = (isPlain ? "__Record" : "__Internref") + clazz.id.toString();
sb.push(typeName);
seenObjectTypes.set(clazz, typeName);
if (isPlain) {
  sb.push(mode == Mode.EXPORT ? "<never>" : "<undefined>");
  this.deferredTypings.push(this.makeRecordType(clazz, mode));
} else {
  this.deferredTypings.push(this.makeInternrefType(clazz));
}
```

**Comment by MaxGraey** [comment]
Thanks!
