### PR TITLE
Progress

### LINKED ISSUE #257: Can't parse call of array element
```ts
export function test(): i32 {
  let a = [(): i32 => 0];
  return a[0]();
}
```
Expected: no error.
Actual:
```
ERROR TS1110: Type expected.

   return a[0]();
                ^
```

### LINKED ISSUE #279: Comparision with constant can't compile when constant is left operand
```ts
export function test(x: i32): bool {
  return 0 < x;
}
```
Error: `ERROR TS2365: Operator '<' cannot be applied to types 'bool' and 'i32'.`

But this works:
```ts
export function test(x: i32): bool {
  return x > 0;
}
```

### LINKED ISSUE #281: Arrays with classes without constructor always have zero length
Without constructor:
```ts
class Ref {}
var arrRef: Ref[] = [new Ref(), new Ref()];
console.logi(arrRef.length); // <--- print 0
```
With constructor:
```ts
class Ref { constructor() {} }
var arrRef: Ref[] = [new Ref(), new Ref()];
console.logi(arrRef.length); // <--- print 2
```

### LINKED ISSUE #285: Namespaces issues after compilation to webassembly module
Below code

```typescript
export declare namespace Draw {
  export function point(x: i32, y: i32): void;
  export function line(x1: i32, y1: i32, x2: i32, y2: i32): void;

  namespace shape {
    export function triangle(x1: i32, y1: i32, x2: i32, y2: i32, x3: i32, y3: i32): void;
  }
}

export function __test(v: i32): void {
  Draw.shape.triangle(v, v, v, v, v, v);
}
```

will produce webassembly that requires:
```javascript
[ { module: 'env', name: 'abort', kind: 'function' },
  { module: 'Draw', name: 'point', kind: 'function' },
  { module: 'Draw', name: 'line', kind: 'function' },
  { module: 'shape', name: 'triangle', kind: 'function' } ] // <--- NOTE HERE a problem
```
would expect something like that:

```javascript
{ module: 'Draw', name: 'shape.triangle', kind: 'function' }
```

and exports:

```javascript
[ { name: 'memory', kind: 'memory' },
  { name: 'Draw.point', kind: 'function' },
  { name: 'Draw.line', kind: 'function' }, 
                      // <--- MISSING Draw.shape.triangle
  { name: '__test', kind: 'function' }]
```

### PR DESCRIPTION
**Pull request by dcodeIO**
This PR includes:

* Update Binaryen to latest
* Add `getFunction` and `newFunction` helpers to loader
* fixes #279
* fixes #285
* <del>fixes #281</del>
* fixes #257
* <del>add table section support to lib/parse</del>

TODO:

- [x] Remove custom binaryen.js build once https://github.com/WebAssembly/binaryen/pull/1692 lands and bump version
- [ ] Make sure WebAssembly Studio runs a compatible binaryen.js version before generating dist files

### CODE REVIEW

File: src/module.ts [hunk 1]
```diff
@@ -646,6 +630,17 @@ export class Module {
     }
   }
 
+  removeGlobal(
+    name: string
+  ): void {
+    var cStr = allocString(name);
+    try {
+      _BinaryenRemoveGlobal(this.ref, cStr);
```
Comment (JounQin) [inline src/module.ts]: `try/finally` is not working for catching the `not defined` error here, you can try it in console of browser or node by yourself

```js
try {
  _BinaryenRemoveGlobal
} finally {}
```

Comment (dcodeIO) [reply src/module.ts]: If you get a "not defined" kind of error there, your Binaryen version is too old. Make sure to use the one in package.json. The try-finally block is there to clean up memory in case of errors only.

Comment (JounQin) [reply src/module.ts]: OK, but it is so weird I've got an error from `cli/asc.js` in https://travis-ci.org/JounQin/wasm-study/builds/441947604#L548, and I could reproduce it on my own machine for a long time today. However, I tried to upgrade all dependencies again just now, it worked... Maybe an issue of `npm/yarn`, still confusing.
