### PR TITLE
Fix type and local confusion when resolving types

### LINKED ISSUE #1684: Name conflicting with generic params in some cases
minimal example:
```ts
function boo<T>(s: T): T { return s }
export function test(string: string): string[] {
  return boo<string>(string);
}
```

Error:
```
ERROR TS2304: Cannot find name 'string'.
    return boo<string>(string);
               ~~~~~~
```

### PR DESCRIPTION
**Pull request by dcodeIO**
Fixes #1684 by hinting whether a lookup is supposed to find a type. Relevant in `resolveType` within functions, where a type can be shadowed by a local.

- [x] I've read the contributing guidelines
- [x] I've added my name and email to the NOTICE file

### CODE REVIEW

File: src/program.ts [hunk 1]
```diff
@@ -3049,23 +3051,23 @@ export class File extends Element {
   }
 
   /* @override */
-  lookupInSelf(name: string): DeclaredElement | null {
-    var element = super.lookupInSelf(name);
+  getMember(name: string): DeclaredElement | null {
```
Comment (MaxGraey) [inline src/program.ts:3054]: Nice!

**Comment by MaxGraey** [comment]
Could you fix lint?

**Review by MaxGraey — APPROVED** [review]
