### PR TITLE
fix: Disallow "any to v128" or "v128 to any" conversions

### LINKED ISSUE #2441: Crashed when using v128 intrinsic and float
Hi,

I don't know it it is still useful for you, but here is a crash of the compiler with a wrong float param in a v128 intrinsic method.

```
export function failing(): void {
  const z = f32x4.splat(0);
  const v: f32 = 0
  v128.add<f32>(z, v);
}
```

```
$ npx --version
7.21.0
```

```
npx asc assembly/images_as_simd_mem4.ts -o public/images_as_simd_mem4.wasm -O3 -Ospeed -t assembly/images_as_simd_mem4.ts.wat --converge --target release --importMemory --sourceMap --enable simd --runtime stub

▌ Whoops, the AssemblyScript compiler has crashed during compile :-(
▌ 
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌ 
▌ /home/v/workspace/react/react-wasm/node_modules/assemblyscript/std/portable/index.js:200
▌     throw new AssertionError(message);
▌           ^
▌ 
▌ AssertionError: void type expected
▌     at null.Z.assert (/home/v/workspace/react/react-wasm/node_modules/assemblyscript/std/portable/index.js:200:11)
▌     at Tr.convertExpression (/home/v/workspace/react/react-wasm/node_modules/assemblyscript/src/compiler.ts:3657:9)
▌     at Tr.compileExpression (/home/v/workspace/react/react-wasm/node_modules/assemblyscript/src/compiler.ts:3498:21)
▌     at null.Rr (/home/v/workspace/react/react-wasm/node_modules/assemblyscript/src/builtins.ts:4678:23)
▌     at Tr.compileCallExpressionBuiltin (/home/v/workspace/react/react-wasm/node_modules/assemblyscript/src/compiler.ts:6574:49)
▌     at Tr.compileCallExpression (/home/v/workspace/react/react-wasm/node_modules/assemblyscript/src/compiler.ts:6335:23)
▌     at Tr.compileExpression (/home/v/workspace/react/react-wasm/node_modules/assemblyscript/src/compiler.ts:3417:21)
▌     at Tr.compileExpressionStatement (/home/v/workspace/react/react-wasm/node_modules/assemblyscript/src/compiler.ts:2448:17)
▌     at Tr.compileStatement (/home/v/workspace/react/react-wasm/node_modules/assemblyscript/src/compiler.ts:2136:21)
▌     at Tr.compileStatements (/home/v/workspace/react/react-wasm/node_modules/assemblyscript/src/compiler.ts:2220:23)
▌ 
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌ 
▌ Thank you!
```

### PR DESCRIPTION
**Pull request by MaxGraey**
Fix #2441

- [x] I've read the contributing guidelines
- [x] I've added my name and email to the NOTICE file

### CODE REVIEW

File: src/compiler.ts [hunk 1]
```diff
@@ -3497,6 +3497,25 @@ export class Compiler extends DiagnosticEmitter {
...
+    if (
+      toType.kind != TypeKind.BOOL &&
+      (toType.kind == TypeKind.V128 || fromType.kind == TypeKind.V128)
+    ) {
+      this.error(
+        DiagnosticCode.Type_0_is_not_assignable_to_type_1,
+        reportNode.range, fromType.toString(), toType.toString()
+      );
+      return module.unreachable();
+    }
```
Comment (dcodeIO) [inline src/compiler.ts:3517]: Can this perhaps be fused into the checks below that already do `isIntegerValue` etc.? `v128` is (and if if isn't yet should be) `isVectorValue` or so.

Comment (MaxGraey) [reply src/compiler.ts:3517]: It could be fused, but it just add a lot of noise. For every case we will need to add `this.error`. While we know that's V128 <-> any disallow for all cases except V128 -> bool. This signifintally simplify everything

Comment (dcodeIO) [reply src/compiler.ts:3517]: I would expect, though, that there'll one day more vector types than just `v128`, and that they all behave about the same, respectively cannot be assigned to each other. So perhaps covering this in a more generic way makes sense?

Comment (MaxGraey) [reply src/compiler.ts:3517]: Ah, I see. So you suggesting jsut switch `toType.kind == TypeKind.V128 || fromType.kind == TypeKind.V128` to `toType.isVectorValue || fromType.isVectorValue`?

Comment (dcodeIO) [reply src/compiler.ts]: That'd be the first step, yeah, and integrating it into the chain of checks below would allow us to handle more common cases first I think, and more easily extend in case conversions between vectors would eventually be possible?

Comment (MaxGraey) [reply src/compiler.ts]: > and more easily extend in case conversions between vectors would eventually be possible?

I'm not sure, as long as it creates more inconvenience and potentially errors. When and if such a moment comes, then it will be possible to reconsider the strategy to a more individualistic one.
