### PR TITLE
fix #2727 Type checker does not detect a signature mismatch

### LINKED ISSUE #2727: Type checker does not detect a signature mismatch
### Bug description

Consider the source code below. The function `expectCallback` needs another function as its argument to produce a number. If we use `callback` this works as expected.

However, if (by mistake) we use a *method* we'd expect the compiler to detect a signature mismatch because methods implicitly have an extra `this` parameter. This is not detected. The code below compiles without issues.

Only during runtime we see the expected problem:
```
RuntimeError: null function or function signature mismatch
    at assembly/index/expectCallback (wasm://wasm/ca122872:wasm-function[50]:0xfee)
```

### Steps to reproduce

```
function callback(a: i32): i32 {
  return a + 3
}

class C {
  callback(a: i32): i32 {
    return a + 3
  }  
}

function expectCallback(c: ((arg0:i32) => i32)): i32 {
  return c(4)
}

export function fut(): i32 {
  //return expectCallback(callback)
  const cl = new C()
  return expectCallback(cl.callback)
}
```

### AssemblyScript version

0.27.5

### PR DESCRIPTION
**Pull request by Changqing-JING**
fixes #2727

### CODE REVIEW

File: tests/compiler/class-member-function-as-parameter.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+  }
+  
+  function expectCallback(c1: (arg0: i32) => i32): i32 {
+    return c1(4);
+  }
+  
+  export function fut(): i32 {
+    const c1 = new C();
+    return expectCallback(c1.callback);
+  }
```
Comment (MaxGraey) [inline tests/compiler/class-member-function-as-parameter.ts:15]: Could we simplify it?
```suggestion
class A {
    a: i32 = 1;
    fn(): i32 { return this.a; }
}
  
function run(fn: () => i32): i32 {
    return fn();
}
  
export function test(): i32 {
    return run((new A()).fn);
}
```

Comment (Changqing-JING) [reply tests/compiler/class-member-function-as-parameter.ts]: @MaxGraey, Thank you! Yes, the code is formated

Comment (MaxGraey) [reply tests/compiler/class-member-function-as-parameter.ts]: Also you should update fixtures via `ASC_FEATURES="*" npm run test:compiler -- --create `

Comment (CountBleck) [reply tests/compiler/class-member-function-as-parameter.ts]: Er, no, don't do that, that'll add other irrelevant files (noExportRuntime.debug.js and co.) to the diff. #2722 should get all that in order, but anyhow, committing every updated fixture isn't a good idea.

File: src/types.ts [hunk 2]
```diff
@@ -1063,7 +1063,7 @@ export class Signature {
     } else {
       // check `this` type (invariant)
       if (thisThisType) {
-        if (targetThisType != targetThisType) return false;
+        if (targetThisType == null) return false;
```
Comment (CountBleck) [inline src/types.ts:1066]: Shouldn't this be:
```suggestion
        if (targetThisType == thisThisType) return false;
```

Comment (Changqing-JING) [reply src/types.ts:1066]: No, target type can be child class of this type. In this case,  `if (targetThisType != thisThisType)` lead to wrong `false`

**Comment by Changqing-JING** [comment]
@MaxGraey All checks passed, can is PR be approved?

**Comment by MaxGraey** [comment]
You should also create `wat` fixture for `class-member-function-as-parameter`

File: src/types.ts (hunk 2 above)
Comment (dcodeIO) [reply src/types.ts:1066]: Looks like `targetThisType != thisThisType` is what's intended here, though. Perhaps what this is missing is a special case for overloads?

**Comment by Changqing-JING** [comment]
This test case expect a compiler failed error. It can't emit wat file

File: src/types.ts (hunk 2 above)
Comment (CountBleck) [reply src/types.ts:1066]: I have no idea about overloads, but I do recall TS being strict in some way about function types being assignable. Something like `(this: B) => void` can't be casted to `(this: A) => void` if `B extends A`, since a different subtype of `A` could be passed to the target function when called.

Instead, I think `(this: A) => void` can be casted to `(this: B) => void` IIRC? So `targetThisType.isAssignableTo(thisThisType)` might be the right answer?

Comment (Changqing-JING) [reply src/types.ts:1066]: Typescript in different with our current case. In AssemblyScript, `this` is a implicit first parameter of the function. In typescript/javascript, `this` is a search chain which can not only refer to the object itself, but may also refer to global/window object. The bug this PR want to fix is due to the `this` type checking, so that we don't need to refer to typescript design.

It seems not possible to create a testcase that cast  `(this: B) => void` to `(this: A) => void`. For example, in following code, the thisThisType is `a\A`, the targetThisType is null.
```typescript
class A{
  public foo():void{}
}

class B extends A{
}

function expectCallback(callback:(arg1: A)=>void):void{

}

export function fut(): void {
  const b = new B();
  expectCallback(b.foo);
}

fut();

```

Comment (CountBleck) [reply src/types.ts:1066]: I just tried that, and it seems that the compiler errors on method declarations that override those from implemented interfaces...is that what you meant, @dcodeIO?

Comment (CountBleck) [reply src/types.ts:1066]: > so that we don't need to refer to typescript design.

Whoops, sorry, I didn't see your comment. We should be mimicking TS semantics (and it shouldn't hurt to).

> but may also refer to global/window object.

This isn't really a concern, since AssemblyScript code is ESM, and in regular JS/TS, ESM implies strict mode, which means `this` cannot refer to the global/window object.

> It seems not possible to create a testcase that cast `(this: B) => void` to `(this: A) => void`.

That *should* throw an error. But `(this: A) => void` to `(this: B) => void` *should* work just fine. [This](https://www.assemblyscript.org/editor#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPWluY3JlbWVudGFsCmNsYXNzIEEgewogICAgZm9vKCk6IHZvaWQgewogICAgICAgIGNvbnNvbGUubG9nKCJBIikKICAgIH0KfQoKY2xhc3MgQiBleHRlbmRzIEEgewogICAgZm9vKCk6IHZvaWQgewogICAgICAgIGNvbnNvbGUubG9nKCJCIikKICAgIH0KfQoKZXhwb3J0IGZ1bmN0aW9uIHRlc3QoKTogdm9pZCB7IAogIGNvbnN0IGEgPSBuZXcgQSgpCiAgY29uc3QgYiA9IG5ldyBCKCkKCiAgYS5mb28uY2FsbChiKSAvLyBzaG91bGQgbG9nICJBIgp9CiMhaHRtbAo8c2NyaXB0IHR5cGU9Im1vZHVsZSI+CiAgICBjb25zdCB7dGVzdH0gPSBhd2FpdCBpbnN0YW50aWF0ZShhd2FpdCBjb21waWxlKCkpCiAgICB0ZXN0KCkKPC9zY3JpcHQ+) should do it.

By playing around with that, it seems like `b.foo.call(a)` errors, but `(b.foo as (this: A) => void).call(a)` compiles when it shouldn't. On the other hand, `a.foo.call(b)` and `(a.foo as (this: B) => void).call(b)` both compile as expected. And in the end, it doesn't even matter, because the compiled output seems to log "B" no matter what...

I'm not sure what to think.

Comment (Changqing-JING) [reply src/types.ts:1066]: `(b.foo as (this: A) => void).call(a)`. is out of scope of this ticket. I just tried to comiple follow example, and the `Signature.isAssignableTo` function is not called. So that the problem you just mentioned should not relavet to current ticket. If we want to fix that, we would better create another ticket to track it.
```typescript
class A {
  public foo(): void {}
}

class B extends A {}

export function fut(): void {
  const a = new A();
  const b = new B();
  (b.foo as (this: A) => void).call(a);
}
```

About the current ticket, it can be summraized as persudo code:
```
if(thisThisType == null && targetThisType == null){
check reset parameters
}else if((thisThisType == null && targetThisType != null) || (thisThisType != null && targetThisType == null)){
return false;
}else{
Not such test case yet.
}
```
Currently there still no test case under `tests` folder, where `thisThisType != null && targetThisType != null`. 
The consern you mentioned are also not that case.

Comment (Changqing-JING) [reply src/types.ts:1066]: @dcodeIO @CountBleck 
I just updated the code, there a 3 cases. 
1. `targetThisType == null && thisThisTyps == null`. In this case, just check further other parameters.
2. `(targetThisType != null && thisThisTyps == null) || (targetThisType == null && thisThisTyps != null)`. In this case, just return false.
3. `targetThisType != null && thisThisTyps != null`. This case only happens when `finalizeOverrideStub`. So that `thisThisType.isAssignableTo(targetThisType)` shall be always true. I just added an assert there.

Moreover, the `(b.foo as (this: A) => void).call(a)` is another case out of this ticket's scope. I tired to compile following sample, but it never used `Signature.isAssignableTo`. If this needs to be fixed, we should create another ticket to track it.
```typescript
class A {
  public foo(): void {}
}

class B extends A {}

export function fut(): void {
  const a = new A();
  const b = new B();
  (b.foo as (this: A) => void).call(a);
}
```

Comment (CountBleck) [reply src/types.ts]: The existing code already handled case 1 and case 2 (just in a more concise manner).

> I tired to compile following sample, but it never used `Signature.isAssignableTo`.

I didn't realize that, whoops! :D
The compiler does crash from your assert by the way:
```ts
class A {
  foo(): void {
    console.log("A");
  }
}

class B extends A {
  foo(): void {
    console.log("B");
  }
}

function foo(): void {
  console.log("nothing");
}

function consume(callback: (this: B) => void): void {
  const b = new B();
  callback.call(b);
}

export function testNull(): void { 
  consume(foo); // This should (and does) error; this is fine.
}

export function testA(): void {
  const a = new A();
  consume(a.foo); // This shouldn't error...but instead it crashes!
}
```

I don't have time at the moment, but I'll reply later with a better example for what I was talking about earlier...

Comment (Changqing-JING) [reply src/types.ts]: @CountBleck 
Yes, case 1 and case 2 are clear and easy to handle. The only problem is case 3. In a previous comment, you mentioned to check if `thisThisType` is assignable to `targetThisType`, I tried as your comment. The conclusion is, base on current test cases, the thisThisType is always child class of targetThisType, so that it doesn't need to be checked. Then I just changed the `if(thisThisType.isAssignableTo(targetThisType))` to assert. 
The assert shall not crash, otherwise it can't pass CI checking.

Comment (CountBleck) [reply src/types.ts]: The snippet above crashes the compiler due to your assert, and that should not happen.

Comment (Changqing-JING) [reply src/types.ts]: @CountBleck Thank you for your help. I sorry I misunderstood your example a bit yesterday, but now I reproduced this crash and fixed it in a new commit. And I have also updated your example into test case.
both `thisThisType.isAssignableTo(targetThisType)` and `targetThisType.isAssignableTo(thisThisType)` need to be checked. The first one for override, the second one for type casting as your example.

Does it looks fine now?

Comment (Changqing-JING) [reply src/types.ts]: Thanks to @HerrCai0907, the `thisThisType.isAssignableTo(targetThisType)` should not be checked in `Signature.isAssignableTo`. Instead, that's caused a bug of `finalizeOverrideStub` in `compiler.ts`.

Comment (CountBleck) [reply src/types.ts]: > Does it looks fine now?

Not quite. I'll do another review...

File: tests/compiler/class-member-function-as-parameter.ts [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+
+export function testA(): void {
+  const a = new A();
+  consume(a.foo); // This shouldn't error
+}
+
+testNull();
+testA();
+
+ERROR("EOF");
```
Comment (CountBleck) [inline tests/compiler/class-member-function-as-parameter.ts:52]: Okay, I simplified the test case:

```suggestion
class A {
  foo(): void {}
}

class B extends A {
  foo(): void {}
}

function foo(): void {}

function consumeA(callback: (this: A) => void): void {}
function consumeB(callback: (this: B) => void): void {}

const a = new A();
const b = new B();

consumeB(a.foo); // shouldn't error
consumeA(foo);   // should error
consumeA(b.foo); // should error

ERROR("EOF");
```

File: tests/compiler/class-member-function-as-parameter.json [hunk 4]
```diff
@@ -0,0 +1,8 @@
+{
+  "asc_flags": [],
+  "stderr": [
+    "TS2322: Type '(this: class-member-function-as-parameter/C, i32) => i32' is not assignable to type '(i32) => i32'.",
+    "TS2322: Type '() => void' is not assignable to type '(this: class-member-function-as-parameter/B) => void'.",
```
Comment (CountBleck) [inline tests/compiler/class-member-function-as-parameter.json:5]: And here are the corresponding errors:
```suggestion
    "TS2322: Type '() => void' is not assignable to type '(this: class-member-function-as-parameter/A) => void'.",
    "TS2322: Type '(this: class-member-function-as-parameter/B) => void' is not assignable to type '(this: class-member-function-as-parameter/A) => void'.",
```

**Review by CountBleck — CHANGES_REQUESTED** [review]
Most of the changes I'm suggesting are about style and don't change functionality.

File: src/compiler.ts [hunk 5]
```diff
@@ -6611,7 +6611,9 @@ export class Compiler extends DiagnosticEmitter {
         if (!overrideInstance.is(CommonFlags.Compiled)) continue; // errored
         let overrideType = overrideInstance.type;
         let originalType = instance.type;
-        if (!overrideType.isAssignableTo(originalType)) {
+
+        assert(originalType.getSignature() != null && overrideType.getSignature() != null);
+        if (!(overrideType.getSignature() as Signature).isAssignableTo(originalType.getSignature() as Signature, true)) {
```
[the remark this answers is not in the document]
Comment (Changqing-JING) [reply src/compiler.ts:6616]: I will in general follow this comment. Use a `const overrideTypeSignature=` and  change `overrideSignature.toString(), originalSignature.toString()`

A small difference is:
`originalType` doesn't have `.signature`, it only has a `signatureReference: Signature | null`. Since there is a getter function of signature already, we should use the getter function instead of the under layer reference.

File: src/types.ts [hunk 6]
```diff
@@ -1051,21 +1051,23 @@ export class Signature {
...
-      if (thisThisType) {
-        if (!targetThisType || !thisThisType.canExtendOrImplement(targetThisType)) {
+
+    if (
+      (thisThisType == null && targetThisType != null) ||
+      (thisThisType != null && targetThisType == null)
+    ) {
+      return false;
+    }else if(thisThisType != null && targetThisType != null){
+      if(checkCompatibleOverride){
```
[the remark this answers is not in the document]
Comment (Changqing-JING) [reply src/types.ts:1061]: @dcodeIO @MaxGraey Dear Maintainers, we do you prefer. The existing check has duplicate code such as
```typescript
} else if (targetThisType) {
        return false;
}
```
It's not a key point, I will follow the style which maintainer like.

File: tests/compiler/class-member-function-as-parameter.ts (hunk 3 above)
Comment (Changqing-JING) [reply tests/compiler/class-member-function-as-parameter.ts:52]: Good change, I will follow it

File: src/compiler.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (CountBleck) [reply src/compiler.ts:6616]: I'm referring to `instance.signature` and `overrideInstance.signature` and not anything on `originalType` and `overrideType`.

File: tests/compiler/class-member-function-as-parameter.json (hunk 4 above)
Comment (Changqing-JING) [reply tests/compiler/class-member-function-as-parameter.json:5]: Good change, I will follow it

File: src/compiler.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (Changqing-JING) [reply src/compiler.ts:6616]: Ahh, understand, I will do it

File: src/types.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (Changqing-JING) [reply src/types.ts:1061]: @CountBleck could you also review this style? In follow code, everything in `if` and `else` are same except `thisThisType.canExtendOrImplement(targetThisType)` and `!argetThisType.isAssignableTo(thisThisType)`. I'm afraid duplicate code doesn't look like better format. But since "better format" and "more readable"  are a bit subjective, I will follow the community's favourite. 

```typescript
    if (checkCompatibleOverride) {
      // check kind of `this` type
      if (thisThisType) {
        if (!targetThisType || !thisThisType.canExtendOrImplement(targetThisType)) {
          return false;
        }
      } else if (targetThisType) {
        return false;
      }
    } else {
      // check `this` type (invariant)
      if (thisThisType) {
        if (!targetThisType || !targetThisType.isAssignableTo(thisThisType)) {
          return false;
        }
      } else if (targetThisType) {
        return false;
      }
    }
```

[the remark this answers is not in the document]
Comment (CountBleck) [reply src/types.ts:1061]: Hm, I see your point. It's that versus...
```ts
    if (thisThisType) {
      if (!targetThisType) return false;
      if (checkCompatibleOverride) {
        // check kind of `this` type
        if (!thisThisType.canExtendOrImplement(targetThisType)) return false;
      } else {
        // check `this` type (contravariant)
        if (!targetThisType.isAssignableTo(thisThisType)) return false;
      }
    } else if (targetThisType) {
      return false;
    }
```
...which looks a bit weird.

This also looks a bit weird:
```ts
    if (thisThisType) {
      if (!targetThisType) return false;
      let compatibleThisType = checkCompatibleOverride
        ? thisThisType.canExtendOrImplement(targetThisType))
        : targetThisType.isAssignableTo(thisThisType);
      if (!compatibleThisType) return false;
    } else if (targetThisType) {
      return false;
    }
```

[the remark this answers is not in the document]
Comment (Changqing-JING) [reply src/types.ts:1061]: Both `checkCompatibleOverride==true` and `checkCompatibleOverride==false` cases needs to return false when one of `targetThisType` and `thisThisType` is null. It's the reason why I put this check in advanced. Otherwise, we need a `if (!targetThisType) return false;` in if branch and another `else if (targetThisType) return false.`

But I think your ` let compatibleThisType = checkCompatibleOverridethisThisType.canExtendOrImplement(targetThisType)): targetThisType.isAssignableTo(thisThisType);` is very good style. We can use it.

Does this version looks better?
```typescript
if (
      (thisThisType == null && targetThisType != null) ||
      (thisThisType != null && targetThisType == null)
    ) {
      return false;
    }else if(thisThisType != null && targetThisType != null){

      const compatibleThisType = checkCompatibleOverride ? thisThisType.canExtendOrImplement(targetThisType)
        : targetThisType.isAssignableTo(thisThisType);
      if (!compatibleThisType) {
        return false;
      }
    }
```

[the remark this answers is not in the document]
Comment (CountBleck) [reply src/types.ts:1061]: > Both `checkCompatibleOverride==true` and `checkCompatibleOverride==false` cases needs to return false when one of `targetThisType` and `thisThisType` is null.

Look closely at the code. That check is already there. Your version of the check is just more verbose.

> Does this version looks better?
I think you need to get introduced to some sort of formatter, because your whitespace is all over the place :P
That alone makes that version look worse.

[the remark this answers is not in the document]
Comment (Changqing-JING) [reply src/types.ts:1061]: I guess your concern is majorly about the `(thisThisType == null && targetThisType != null) || (thisThisType != null && targetThisType == null)`. It's the "verbose" you said, because it checks `thisThisType == null` and `thisThisType != null` twice. But `if (!targetThisType) return false` and `else if (targetThisType) return false` also both `return false`, it's perhaps the "wired" you mean.

Then how abut this?
```typescript
if (
      (thisThisType || targetThisType) && !(thisThisType && thisThisType)
    )
```

[the remark this answers is not in the document]
Comment (Changqing-JING) [reply src/types.ts:1061]: sure，we can use this one. Currently I'm away of my laptop. I will commit fix of all your comments tomorrow

File: src/types.ts (hunk 2 above)
Comment (Changqing-JING) [reply src/types.ts]: @CountBleck Your comments are fixed in new commit

**Review by CountBleck — CHANGES_REQUESTED** [review]
Just some minor style issues.

File: src/types.ts [hunk 7]
```diff
@@ -1051,22 +1051,15 @@ export class Signature {
...
-      } else if (targetThisType) {
+
+    if (thisThisType != null && targetThisType != null){
+      const compatibleThisType = checkCompatibleOverride ? thisThisType.canExtendOrImplement(targetThisType)
+        : targetThisType.isAssignableTo(thisThisType);
+      if (!compatibleThisType) {
         return false;
       }
+    }else if (thisThisType || targetThisType){
+      return false;
```
[the remark this answers is not in the document]
Comment (Changqing-JING) [reply src/types.ts]: Done

File: src/compiler.ts [hunk 8]
```diff
@@ -6609,17 +6609,18 @@ export class Compiler extends DiagnosticEmitter {
       for (let i = 0, k = overrideInstances.length; i < k; ++i) {
         let overrideInstance = overrideInstances[i];
         if (!overrideInstance.is(CommonFlags.Compiled)) continue; // errored
-        let overrideType = overrideInstance.type;
-        let originalType = instance.type;
-        if (!overrideType.isAssignableTo(originalType)) {
+
+        const overrideSignature = overrideInstance.signature;
+        const originalSignature = instance.signature;
```
[the remark this answers is not in the document]
Comment (Changqing-JING) [reply src/compiler.ts]: Done

File: src/types.ts (hunk 2 above)
Comment (Changqing-JING) [reply src/types.ts]: @CountBleck format and style are refined

File: src/types.ts [hunk 9]
```diff
@@ -1051,22 +1051,14 @@ export class Signature {
...
-      }
-    } else {
-      // check `this` type (invariant)
-      if (thisThisType) {
-        if (targetThisType != targetThisType) return false;
-      } else if (targetThisType) {
-        return false;
-      }
+
+    if (thisThisType != null && targetThisType != null){
```
Comment (CountBleck) [inline src/types.ts:1055]: You are very close. You're missing a space before the opening brace on this line, and you're missing two spaces in the `else if` line: one right before `else if`, and one before the opening brace.

I should have noticed this earlier, but use `thisThisType && targetThisType` instead of `thisThisType != null && targetThisType != null`.

@dcodeIO Is this ternary I proposed okay with you?

Comment (Changqing-JING) [reply src/types.ts]: Done

Comment (Changqing-JING) [reply src/types.ts]: @dcodeIO @MaxGraey ping maintainer.

**Review by CountBleck — APPROVED** [review]
Seems fine.

**Review by HerrCai0907 — APPROVED** [review]
LGTM. But maybe add test for `B implement A`

**Comment by CountBleck** [comment]
> LGTM. But maybe add test for `B implement A`

It might be redundant, since the same code path is used.
