### PR TITLE
loader: Fix TypedArray view not considering .byteLength of slices

### LINKED ISSUE #2091: Loader cannot access the subarray correctly
I am trying to use Loader to access the TypedArray of wasm.
I can access the original array, but there is a problem when accessing its subarray.
When I get the subarray with `__getArrayView`, it appears as an empty array.
I guess that it is probably a problem of Loader, since subarray is working correctly inside wasm.
I think it would be useful to have access in this way.

MWE: [AssemblyScript Editor](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1ub25lJnJ1bnRpbWU9aW5jcmVtZW50YWwmZXhwb3J0UnVudGltZQpsZXQgYXJyOiBJbnQzMkFycmF5IHwgbnVsbCA9IG51bGwKbGV0IHN1YmFycjogSW50MzJBcnJheSB8IG51bGwgPSBudWxsCgpleHBvcnQgZnVuY3Rpb24gZ2EoKTogSW50MzJBcnJheSB7CiAgaWYgKCFhcnIpIHsKICAgIGFyciA9IG5ldyBJbnQzMkFycmF5KDEwKQogIH0KICByZXR1cm4gYXJyIGFzIEludDMyQXJyYXkKfQoKZXhwb3J0IGZ1bmN0aW9uIGdiKCk6IEludDMyQXJyYXkgewogIGlmICghc3ViYXJyKSB7CiAgICBzdWJhcnIgPSBnYSgpLnN1YmFycmF5KDUpCiAgfQogIHJldHVybiBzdWJhcnIgYXMgSW50MzJBcnJheQp9CgpleHBvcnQgZnVuY3Rpb24gZ2MoKTogdm9pZCB7CiAgY29uc3QgcyA9IGdiKCkKICBzWzBdID0gNDIKfQojIWh0bWwKPHRleHRhcmVhIGlkPSJvdXRwdXQiIHN0eWxlPSJoZWlnaHQ6IDEwMCU7IHdpZHRoOiAxMDAlIiByZWFkb25seT48L3RleHRhcmVhPgo8c2NyaXB0Pgpsb2FkZXIuaW5zdGFudGlhdGUobW9kdWxlX3dhc20sIHsgLyogaW1wb3J0cyAqLyB9KQogIC50aGVuKCh7IGV4cG9ydHMgfSkgPT4gewogICAgY29uc3Qgb3V0cHV0ID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignI291dHB1dCcpCiAgICBvdXRwdXQudmFsdWUgPSAnJwogICAgdHJ5IHsKICAgICAgY29uc3QgcHRyID0gZXhwb3J0cy5fX3BpbihleHBvcnRzLmdhKCkpCiAgICAgIGV4cG9ydHMuZ2MoKQogICAgICBjb25zdCBhcnIgPSBleHBvcnRzLl9fZ2V0QXJyYXlWaWV3KHB0cikKICAgICAgb3V0cHV0LnZhbHVlICs9IGBhcnI6IGxlbmd0aD0ke2Fyci5sZW5ndGh9LCBieXRlTGVuZ3RoPSR7YXJyLmJ5dGVMZW5ndGh9LCBkYXRhPSR7YXJyfVxuYAogICAgICBjb25zdCBzcHRyID0gZXhwb3J0cy5fX3BpbihleHBvcnRzLmdiKCkpCiAgICAgIGNvbnN0IHN1YmFyciA9IGV4cG9ydHMuX19nZXRBcnJheVZpZXcoc3B0cikKICAgICAgb3V0cHV0LnZhbHVlICs9IGBzdWJhcnI6IGxlbmd0aD0ke3N1YmFyci5sZW5ndGh9LCBieXRlTGVuZ3RoPSR7c3ViYXJyLmJ5dGVMZW5ndGh9LCBkYXRhPSR7c3ViYXJyfVxuYAogICAgfSBjYXRjaCAoZXJyKSB7CiAgICAgIG91dHB1dC52YWx1ZSA9IGAke2Vycn1gCiAgICB9CiAgfSkKPC9zY3JpcHQ+)
```ts
// module.ts
let arr: Int32Array | null = null
let subarr: Int32Array | null = null

export function ga(): Int32Array {
  if (!arr) {
    arr = new Int32Array(10)
  }
  return arr as Int32Array
}

export function gb(): Int32Array {
  if (!subarr) {
    subarr = ga().subarray(5)
  }
  return subarr as Int32Array
}

export function gc(): void {
  const s = gb()
  s[0] = 42
}
```
```html
// index.html
<textarea id="output" style="height: 100%; width: 100%" readonly></textarea>
<script>
loader.instantiate(module_wasm, { /* imports */ })
  .then(({ exports }) => {
    const output = document.querySelector('#output')
    output.value = ''
    try {
      const ptr = exports.__pin(exports.ga())
      exports.gc()
      const arr = exports.__getArrayView(ptr)
      output.value += `arr: length=${arr.length}, byteLength=${arr.byteLength}, data=${arr}\n`
      const sptr = exports.__pin(exports.gb())
      const subarr = exports.__getArrayView(sptr)
      output.value += `subarr: length=${subarr.length}, byteLength=${subarr.byteLength}, data=${subarr}\n`
    } catch (err) {
      output.value = `${err}`
    }
  })
</script>
```
Expected Behavior:
```
arr: length=10, byteLength=40, data=0,0,0,0,0,42,0,0,0,0
subarr: length=5, byteLength=20, data=42,0,0,0,0
```
Actual behavior (the subarray appears as an empty array):
```
arr: length=10, byteLength=40, data=0,0,0,0,0,42,0,0,0,0
subarr: length=0, byteLength=0, data=
```

### PR DESCRIPTION
**Pull request by dcodeIO**
fixes #2091

- [x] I've read the contributing guidelines
- [x] I've added my name and email to the NOTICE file

### CODE REVIEW

File: lib/loader/index.js [hunk 1]
```diff
@@ -288,7 +288,7 @@ function postInstantiate(extendedExports, instance) {
     const buffer = memory.buffer;
     const U32 = new Uint32Array(buffer);
     const bufPtr = U32[ptr + ARRAYBUFFERVIEW_DATASTART_OFFSET >>> 2];
-    return new Type(buffer, bufPtr, U32[bufPtr + SIZE_OFFSET >>> 2] >>> alignLog2);
+    return new Type(buffer, bufPtr, U32[ptr + ARRAYBUFFERVIEW_BYTELENGTH_OFFSET >>> 2] >>> alignLog2);
```
Comment (MaxGraey) [inline lib/loader/index.js:291]: How about?
```ts
    return new Type(
      buffer, 
      U32[ptr + ARRAYBUFFERVIEW_DATASTART_OFFSET >>> 2], 
      U32[ptr + ARRAYBUFFERVIEW_BYTELENGTH_OFFSET >>> 2] >>> alignLog2
    );
```

Comment (dcodeIO) [reply lib/loader/index.js:291]: Oh, right, `bufPtr` only has one use now. Will change!
