### PR TITLE
Try to fix TS1005 unexpected error

### LINKED ISSUE #148: Unexpected TS1005 error
Code for reproduction:
```ts
const t: bool = <u32>10 < (u32.MAX_VALUE / 10);
```
Output:
```ts
ERROR TS1005: ')' expected.

 const t: bool = <u32>10 < (u32.MAX_VALUE / 10);
                            ~~~
```

### PR DESCRIPTION
**Pull request by MaxGraey**
Fix #148

### CODE REVIEW

File: src/parser.ts [hunk 1]
```diff
@@ -645,10 +645,14 @@ export class Parser extends DiagnosticEmitter {
...
-          DiagnosticCode._0_expected,
-          tn.range(), ")"
-        );
+        if (isSignature) {
+          this.error(
+            DiagnosticCode._0_expected,
+            tn.range(), ")"
+          );
+        } else {
+          tn.reset(state);
```
Comment (MaxGraey) [inline src/parser.ts]: Is it really need this?
