### PR TITLE
fix: Adding duplicate identifier check in function signatures

### LINKED ISSUE #1864: Duplicate identifiers in function signature is considered valid code
The following should not compile 

```ts
function id<T>(a: T, a: T): T {
  return a;
}

export const a = id<i32>(1, 2);
```

**Expected**
Duplicate identifier 'a'

**Actual**
Compiles successfully.

### PR DESCRIPTION
**Pull request by MaxGraey**
Fix #1864 

- [x] I've read the contributing guidelines

### CODE REVIEW

File: src/parser.ts [hunk 1]
```diff
@@ -1576,6 +1582,8 @@ export class Parser extends DiagnosticEmitter {
     startPos: i32 = -1,
     signatureStart: i32 = -1
   ): FunctionExpression | null {
+    this.checkFunctionParameterDuplicates(parameters);
```
Comment (MaxGraey) [inline src/parser.ts:1585]: @dcodeIO I moved check to `parseFunctionExpressionCommon` from `parseFunctionExpression`. But may be this cause to redundant checks. Need your advise

**Comment by dcodeIO** [comment]
I would like to suggest to implement the check at compiler level, that is when a function is actually compiled, since these are not necessarily syntax errors, but semantic errors.

**Review by dcodeIO — APPROVED** [review]
👍
