### PR TITLE
Fix fromCharCodes & fromCodePoints polyfills

### LINKED ISSUE #1324: Maximum call stack size exceeded when compiling optimised code
I get a weird error when compiling my code with optimisation flags **-O3 --noAssert**
Unfortunately I have not succeed reproducing the issue with a simple code fragment...
My codebase is in this repository:  https://github.com/alexvictoor/HdrHistogramJS

If I run "npm run asbuild:optimized" adding a **--noAssert** flag compilation fails.
If I remove the [call to clz()](https://github.com/alexvictoor/HdrHistogramJS/blob/master/assembly/Histogram.ts#L263) and replace it by the commented code fragment below, everything is fine...

### PR DESCRIPTION
**Pull request by MaxGraey**
Potentially fix #1324 

- [x] I've read the contributing guidelines

### CODE REVIEW

File: std/portable/index.js [hunk 1]
```diff
@@ -198,11 +198,38 @@ globalScope["changetype"] = function changetype(value) {
 };
 
 String["fromCharCodes"] = function fromCharCodes(arr) {
-  return String.fromCharCode.apply(String, arr);
+  const CHUNKSIZE = 1 << 14;
```
Comment (dcodeIO) [inline std/portable/index.js:201]: I remember that I did `1 << 13` there in the past, but I don't remember exactly how I figured out this limit. Not a huge difference, but perhaps staying conservative here is worth it so we don't run into issues if this function is called in a code path already quite deep into the stack. Wdyt?

Comment (MaxGraey) [reply std/portable/index.js:201]: I'm ok with `1 << 13` as well. It's not big deal.

Comment (MaxGraey) [reply std/portable/index.js]: Not sure why, but on latest node (not lts) new chunked approach slowdown tests. Try to increase `1 << 13` to `1 << 15`

**Comment by MaxGraey** [comment]
Alright. It seems simple loops have pretty good performance and much simpler. WDYT?

**Comment by dcodeIO** [comment]
Hmm, question is how well it will perform in the worst case I guess. Let's say someone doesn't use a browser or runtime JITing these well. Or in an environment where the runtime is recent but JITing is disabled. It's unlikely, but if it happens, it can be really slow.

`String.fromCodePoints` mostly exists because there is no good alternative, more a feature for users than for the compiler itself.

**Comment by MaxGraey** [comment]
I reverted recent changes already) Performance of CI is quite unstable. Will be great have online benchmark for compiler's speed

**Comment by dcodeIO** [comment]
Also, now I'm wondering if we can use [TextDecoder](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder)?

**Comment by MaxGraey** [comment]
`TextDecoder` also an option. But I prefer leave this as is currently. May be in future with more proper compiler's speed benchmark...

**Comment by dcodeIO** [comment]
Sounds good to me :)

File: std/portable/index.js [hunk 2]
```diff
@@ -198,11 +198,38 @@ globalScope["changetype"] = function changetype(value) {
...
+  let len = arr.length;
+  if (len <= CHUNKSIZE) {
+    return String.fromCodePoints.apply(String, arr);
+  }
+  let index = 0;
+  let parts = '';
+  do {
+    const last = arr[index + CHUNKSIZE - 1];
+    const size = last >= 0xD800 && last < 0xDC00 ? CHUNKSIZE - 1 : CHUNKSIZE;
+    parts += String.fromCharCode.apply(String, arr.slice(index, index += size));
```
Comment (dcodeIO) [inline std/portable/index.js:229]: Is this correct now, given that inputs are code points here?

Comment (MaxGraey) [reply std/portable/index.js]: Yeah, need use same approach as for `fromCharCodes` and just use `String.fromCodePoint` instead `String.fromCharCode`

File: std/portable/index.js [hunk 3]
```diff
@@ -198,11 +198,39 @@ globalScope["changetype"] = function changetype(value) {
...
+      arr.slice(index, Math.min(index + CHUNKSIZE, len))
+    );
+    index += CHUNKSIZE;
+  }
+  return parts;
 };
 
 String["fromCodePoints"] = function fromCodePoints(arr) {
-  return String.fromCodePoint.apply(String, arr);
+  const CHUNKSIZE = 1 << 15;
```
Comment (dcodeIO) [inline std/portable/index.js:219]: Also, my worries about making this too large aren't so much about speed, but about reasonably guaranteeing not to overrun the stack in a fix that is supposed to fix overrunning the stack. We can't really tell if these functions will be used somewhere deeper down the stack, even though it might work with `1 << 15` with how the compiler calls them.

Comment (MaxGraey) [reply std/portable/index.js:219]: How about `1 << 14`? I guess it's quite optimal and allow up to 3 level stack nesting

Comment (dcodeIO) [reply std/portable/index.js:219]: We can try if you wish, but chances are that people will run into problems and give up without ever reporting the problem. Perhaps I'm favoring being safe too much there?

Comment (MaxGraey) [reply std/portable/index.js]: Alright) I guess 1 << 13 shouldn't cause any problems

**Comment by dcodeIO** [comment]
Thanks :)
