### PR TITLE
Use fully qualified names in generic types

### LINKED ISSUE #539: ERROR TS2322: Type 'FooBar' is not assignable to type 'FooBar'.
```
➜  near-bindgen git:(number-types) ✗ ./test.sh 
+ BASEDIR=../..
+ ../../bin/asc model.ts --nearFile model_near.ts
+ ../../bin/asc main.ts --nearFile main_near.ts
ERROR TS2322: Type 'FooBar' is not assignable to type 'FooBar'.

     return foobars.map<ContainerClass>((it: FooBar, i: i32, arr: Array<FooBar>): ContainerClass => {
                                         ~~~~~~~~~~
 in main.ts(35,40)

ERROR: Compile error
    at Object.main (/Users/vg/Documents/assemblyscript/cli/asc.js:477:21)
    at Object.<anonymous> (/Users/vg/Documents/assemblyscript/bin/asc:4:60)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
```

For repro see https://github.com/nearprotocol/assemblyscript/pull/23

Go to `tests/near-bindgen` and run `./test.sh`. 

It looks like https://github.com/AssemblyScript/assemblyscript/pull/489 doesn't fully solve all name clash issues.

### PR DESCRIPTION
**Pull request by dcodeIO**
This PR addresses a probable cause for the `Type 'Foo' is not assignable to type 'Foo'` issue. See also [this comment](https://github.com/AssemblyScript/assemblyscript/issues/539#issuecomment-473518110).

most likely fixes #539 / cc @vgrichina

### CODE REVIEW

**Comment by vgrichina** [comment]
Looks like compiler OOMs after merging this, see:
https://github.com/nearprotocol/assemblyscript/tree/hang-demo/tests/near-bindgen

Trying to compile `main.ts` hangs and goes out of memory.

**Comment by dcodeIO** [comment]
Do you have a crash dump?

**Comment by vgrichina** [comment]
@dcodeIO 

```
+ ../../bin/asc main.ts -o test.wasm

<--- Last few GCs --->

[5889:0x103802200]    25868 ms: Scavenge 1397.1 (1422.7) -> 1396.7 (1423.7) MB, 3.0 / 0.0 ms  (average mu = 0.095, current mu = 0.047) allocation failure 
[5889:0x103802200]    27214 ms: Mark-sweep 1397.4 (1423.7) -> 1397.0 (1423.2) MB, 1336.9 / 0.0 ms  (average mu = 0.070, current mu = 0.020) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0xd163e0dbe3d]
Security context: 0x280e1b49e6e1 <JSObject>
    1: /* anonymous */ [0x280e7037eaa9] [/Users/vg/Documents/assemblyscript/src/diagnostics.ts:~227] [pc=0xd163e69d103](this=0x280e533ca561 <Parser map = 0x280ed4b198b1>,code=1003,category=2,range=0x280e69102999 <Range map = 0x280ed4b31c19>,relatedRange=0x280e6c4022b1 <null>,arg0=0x280e6c4022b1 <null>,arg1=0x280e6c4022b1 <null>,arg2=0x280e6c4022b1 <null>)
   ...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003ae75 node::Abort() [/Users/vg/n/bin/node]
 2: 0x10003b07f node::OnFatalError(char const*, char const*) [/Users/vg/n/bin/node]
 3: 0x1001a7ae5 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/vg/n/bin/node]
 4: 0x100572ef2 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/vg/n/bin/node]
 5: 0x1005759c5 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/vg/n/bin/node]
 6: 0x10057186f v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/vg/n/bin/node]
 7: 0x10056fa44 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/vg/n/bin/node]
 8: 0x10057c2dc v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/vg/n/bin/node]
 9: 0x10057c35f v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/vg/n/bin/node]
10: 0x10054b6f6 v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Heap::RootListIndex, int, v8::internal::Object*, v8::internal::PretenureFlag) [/Users/vg/n/bin/node]
11: 0x1004f2b1e v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::GrowCapacity(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/Users/vg/n/bin/node]
12: 0x10078daff v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/vg/n/bin/node]
13: 0xd163e0dbe3d 
./test.sh: line 6:  5889 Abort trap: 6           $BASEDIR/bin/asc main.ts -o test.wasm
```

Is issue non-reproducible on your side?

File: src/types.ts [hunk 1]
```diff
@@ -637,17 +637,15 @@ export class Signature {
...
     var index = 0;
     var thisType = this.thisType;
     if (thisType) {
-      if (includeThis) {
-        sb.push("this: ");
-        sb.push(thisType.toString());
-        index = 1;
-      }
+      sb.push("this: ");
+      sb.push(thisType.toString());
```
Comment (MaxGraey) [inline src/types.ts]: It seems this cause to recursively calls: Signature#toString -> Type#toString() -> Signature#toString ...
May be should revert back `includeThis: bool = false`?

Comment (dcodeIO) [reply src/types.ts]: Are you sure about this? `thisType` is never a signature I think.

**Comment by dcodeIO** [comment]
Can confirm, seems to hang in `Parser#parseClassOrInterface` on

```ts
    if (!tn.skip(Token.CLOSEBRACE)) {
      do {
        let member = this.parseClassMember(tn, declaration);
        if (member) members.push(<DeclarationStatement>member);
      } while (!tn.skip(Token.CLOSEBRACE)); // HERE
    }
```

**Comment by dcodeIO** [comment]
Seems there is a (possibly generated) method somewhere looking like

```ts
setString(name: string, value: ~lib/string/String): void
```

which fails to parse because it uses a fully qualified type name for `value`. The compiler shouldn't hang on something like this ofc, but this issue must be addressed as well.

**Comment by dcodeIO** [comment]
For reference, this is how I debugged this: In `test.sh`, change the asc invocation to

```sh
node --inspect $BASEDIR/bin/asc model.ts --nearFile model_near.ts
node --inspect $BASEDIR/bin/asc main.ts -o test.wasm
```

and navigate to `chrome://inspect` in Chromium. Now, when test.sh is run, the inspect tab will show a prompt to inspect the process, which upon connect yields a detailed call stack right before OOM with code locations. Everything else was just a matter of `console.log`ging `tn.source.text.substring(tn.pos - 64, tn.pos + 64)` to see what's currently processed.

File: src/types.ts (hunk 1 above)
Comment (dcodeIO) [reply src/types.ts]: added an assertion to be sure :)

**Comment by vgrichina** [comment]
wow, `node --inspect` is really cool, last time I tried debugging node (few years ago) it's been far more involved

**Comment by vgrichina** [comment]
```
ERROR TS1003: Identifier expected.

 setString(name: string, value: ~lib/string/String): void {
                                ~
 in model_near.ts(225,31)
```

Awesome, fix worked!

**Comment by dcodeIO** [comment]
Let me know when you think this PR is good to merge :)

**Comment by vgrichina** [comment]
@dcodeIO fix works for me, should be good to merge
