### PR TITLE
fix: More proper Math.round

### LINKED ISSUE #1856: a small bug in Math.round with some values between 2**52 and 2**53
`Math.round(2**53 - 1)` should return `2**53 - 1`

### PR DESCRIPTION
**Pull request by MaxGraey**
Previous implementation  was incorrect for maximum mantissa values.

Edge cases current:
```ts
Math.round(+9007199254740991) -> +9007199254740992
Math.round(-9007199254740991) -> -9007199254740990
```

Edge cases fixed:
```ts
Math.round(+9007199254740991) -> +9007199254740991
Math.round(-9007199254740991) -> -9007199254740991
```

Fix #1856 

- [x] I've read the contributing guidelines

### CODE REVIEW

File: std/assembly/math.ts [hunk 1]
```diff
@@ -1437,7 +1437,8 @@ export namespace NativeMath {
   // @ts-ignore: decorator
   @inline
   export function round(x: f64): f64 {
-    return builtin_copysign<f64>(builtin_floor<f64>(x + 0.5), x);
+    let roundUp = builtin_ceil<f64>(x);
+    return select<f64>(roundUp, roundUp - 1.0, roundUp - 0.5 <= x);
```
Comment (Yaffle) [inline std/assembly/math.ts:1441]: the `roundUp - 0.5 <= x` is a littler harder to think out than `roundUp - x <= 0.5` as the second one has no inexact operations
