### PR TITLE
[Fix] Static class callback fixes #720

### LINKED ISSUE #720: [Bug] Static class method cannot be used as callback
```
ERROR AS218: Cannot access method 'compare' without calling it as it requires 'this' to be set.

     actual.sort(Buffer.compare);
                 ~~~~~~~~~~~~~~
 in tests/buffer.spec.ts(60,16)
```

Thoughts?

EDIT: Found here: https://github.com/AssemblyScript/node/pull/7

### PR DESCRIPTION
**Pull request by jtenner**
This is my first pass at fixing #720.

Thoughts?

### CODE REVIEW

File: src/compiler.ts [hunk 1]
```diff
@@ -7989,9 +7989,17 @@ export class Compiler extends DiagnosticEmitter {
         );
       }
       case ElementKind.FUNCTION_PROTOTYPE: {
+        let prototypeInstance = <FunctionPrototype>target;
+
+        if (prototypeInstance.is(CommonFlags.STATIC)) {
+          let instance = this.compileFunctionUsingTypeArguments(prototypeInstance, [])!;
```
Comment (dcodeIO) [inline src/compiler.ts]: This can return `null`, in which case an `unreachable` should be emitted. Also, providing `alternativeReportNode = propertyAccess` will refer to a better code location in the error case, as it will otherwise report on the original function, which misses a clue where the error actually happened.

File: src/compiler.ts [hunk 2]
```diff
@@ -7989,9 +7989,17 @@ export class Compiler extends DiagnosticEmitter {
         );
       }
       case ElementKind.FUNCTION_PROTOTYPE: {
+        let prototypeInstance = <FunctionPrototype>target;
```
Comment (dcodeIO) [inline src/compiler.ts]: Typically named just "prototype" in other parts of the compiler.

**Comment by dcodeIO** [comment]
LGTM with the comments addressed :)

**Comment by jtenner** [comment]
This is definitely my first time trying to work with the compiler. Thanks for the information.

File: src/compiler.ts (hunk 1 above)
Comment (jtenner) [reply src/compiler.ts]: Should we emit a compiler error here instead of `unreachable()` when the return is `null`? I'm not sure what returning null actually means.

Also the property node fix makes perfect sense. I'll get around to this soon.

Comment (dcodeIO) [reply src/compiler.ts]: What happens in situations like these is that some part of the code finds that an operation is invalid, so it emits a diagnostic and returns `null`. That's the case here as well: An error has already been emitted if `compileFunctionUsingTypeArguments` returns `null`.

Comment (dcodeIO) [reply src/compiler.ts]: If you are interested in seeing what happens in such a case, make the function being used generic. That'd result in a diagnostic in the resolve step of `compileFunctionUsingTypeArguments`, which returns `null`, making `compileFunctionUsingTypeArguments` return null, leading to an `unreachable` here.

Comment (jtenner) [reply src/compiler.ts]: That makes perfect sense. Thank you for taking the time to explain this.

File: src/compiler.ts (hunk 2 above)
Comment (jtenner) [reply src/compiler.ts]: All set!

File: src/compiler.ts (hunk 1 above)
Comment (jtenner) [reply src/compiler.ts]: All set!

**Comment by dcodeIO** [comment]
Thanks! :)
