### PR TITLE
Use ES2016 as target for src and transforms

### LINKED ISSUE #978: Transforms using ExportsWalker are broken in 0.8.1
Given a transform function that uses the `ExportsWalker` class exported by AssemblyScript, when running it using `asc` using 0.8.1, a runtime error occurs.

E.g. given transform file `BarTransform.ts`,
```ts
import { Transform } from "assemblyscript/cli/transform";
import { ExportsWalker } from "assemblyscript";

class FooWalker extends ExportsWalker {
  ...
}

export = class BarTransform extends Transform {
  afterParse(parser: Parser) {
    ...
  }

  afterCompile(module: Module) {
    const walker = new FooWalker(this.program);
    ...
  }
}
```
run with `asc foo.ts -b build/foo.wasm --transform=BarTransform.ts` will yield an error with:
```
ERROR: TypeError: Class constructor o cannot be invoked without 'new'
```

Running the same transform with 0.8.0 works as expected.

Looking at the exports, it appears that the `assemblyscript` package is exporting `ExportsWalker` as an ES6 class in 0.8.1 but as an ES5 function in 0.8.0. I think this is caused by a change in `std/portable.json` where the target was changed from `es5` in 0.8.0 to `esnext` in 0.8.1.

Also relevant, Typescript transform files are transpiled using default compiler settings, one of which is to target es5, which results in Typescript transform files not being able to initialize exported classes from the `assemblyscript` package like `ExportsWalker`. That hasn't changed between versions.

There are two approaches that I think would fix this problem:
1. Use an `es5` target when building the `assemblyscript` package
2. Target `esnext` when transpiling Typescript transform files

### PR DESCRIPTION
**Pull request by jeffcharles**
Fixes #978. src and transforms will now have the same compile target so
transforms can consume classes exported by src.

### CODE REVIEW

File: cli/asc.js [hunk 1]
```diff
@@ -219,7 +219,9 @@ exports.main = function main(argv, options, callback) {
     let transformArgs = args.transform;
     for (let i = 0, k = transformArgs.length; i < k; ++i) {
       let filename = transformArgs[i].trim();
-      if (/\.ts$/.test(filename)) require("ts-node").register({ transpileOnly: true, skipProject: true });
+      if (/\.ts$/.test(filename)) {
+        require("ts-node").register({ transpileOnly: true, skipProject: true, compilerOptions: { target: "ES2016" } });
```
Comment (dcodeIO) [inline cli/asc.js]: There is another ts-node invocation at the start of the file loading the compiler in a development setup, that should probably use the same target.

**Comment by dcodeIO** [comment]
LGTM with the comment addressed :)

File: cli/asc.js (hunk 1 above)
Comment (MaxGraey) [reply cli/asc.js]: I guess it could be solved in other PR from me: https://github.com/AssemblyScript/assemblyscript/pull/985/files#diff-1d2bb562554675174e389bb738b930cdR223

**Comment by dcodeIO** [comment]
Thanks! :)
