### PR TITLE
BREAKING CHANGE: ESM, JS bindings, triple equals and general cleanup

### LINKED ISSUE #531: Remove expression variant from isInteger, isFloat etc. for consistency
Currently, most static type evaluation builtins take either a type argument or an argument, but the second case is unsound in that the expression is evaluated for its type but ultimately ignored. For example, the following code will never execute the expression because the call's result is supposed to evaluate to a constant with no place to put the expression:

```ts
var a: i32 = 0;
if (isInteger(a = 1)) {
  // a is 0
}
// a is 0
```

I therefore propose to remove the second case. Or does anyone actually **have to** use the second case for a good reason, somewhere?

### LINKED ISSUE #856: Potentially eliminating the case of ===
It has been suggested various times to align the use of the `===` operator to what JS/TS would do, which came also up again in a recent issue (I don't remember which one), suggesting to replace our special `===` semantics with `changetype<usize>(a) == changetype<usize>(b)` in standard library code, which is about the only place where this is of importance. Overall this change would make `===` and `==` behave exactly the same for string operands and drop the special meaning of `someObject === someObject`, replacing it with something else where necessary.

Considering the general confusion introduced by this, I am leaning towards this solution. Thoughts?

### LINKED ISSUE #1306: Investigate switching all of AS to ESM
While the CommonJS and ESM compatibility story in node appears to be a disaster still, ESM is getting more and more traction and since AS requires relatively modern environments anyway, we should aim at making the switch rather sooner than later.

Related issues: https://github.com/AssemblyScript/assemblyscript/issues/1207

### LINKED ISSUE #1954: unable to import from installed library in node_modules without relative path
#1679 got closed by the _super ugly stupid_ stale bot (:robot::boom:• • • • :boom::gun:), so continuing here:

I just tried this on 0.19.5 and I still get an error:

```ts
import {...} from 'asdom/assembly/index'
```

```
> asc assembly/index.ts --target debug --exportRuntime --exportTable

ERROR TS6054: File '~lib/asdom/assembly/index.ts' not found.

 } from 'asdom/assembly/index'
        ~~~~~~~~~~~~~~~~~~~~~~
 in assembly/index.ts(9,8)

FAILURE 1 parse error(s)
```

This works though:

```ts
import {...} from '../node_modules/asdom/assembly/index'
```

Reproduction:

```sh
git clone https://github.com/lume/asdom.git
cd asdom
git checkout unable-to-import
npm install
cd example
npm install
npm run dev // ERROR
```

----

The following works, but TypeScript shows red squigglies and intellisense breaks because AssemblyScript projects are not set up by default to satisfy TypeScript node resolution:

```js
import {...} from 'asdom' // red squigglies all over!
```

The following doesn't work in AS, but it is proper and TypeScript will see the correct imports and we will get working intellisense:

```js
import {...} from 'asdom/assembly/index' // Intellisense works, but not AS
```

### LINKED ISSUE #2099: Crash when wasmtime invokes specific function
I am encountering a crash in Wasm generated with recent versions of AssemblyScript when I invoke a function other than the default entry point.

**Repro setup**

I am testing with AssemblyScript 0.19.17 and Wasmtime 0.30.0.

My `index.ts` is as follows:

```typescript
import "wasi";

import { Console } from "as-wasi";

export function foo(): void {
    Console.log("foo");
}
```

My `package.json` contains the following scripts:

```
    "build:untouched": "asc assembly/index.ts --target debug --use abort=wasi_abort",
    "build:optimized": "asc assembly/index.ts --target release --use abort=wasi_abort",
    "build": "npm run build:untouched && npm run build:optimized"
```

**Symptoms**

What I ran:

* `npm run build`
* `wasmtime run --invoke foo ./build/untouched.wasm`

Expected output: `foo`

Actual output: many (stack overflow amount?) lines of error dump which repeats the following lines:

```
         21386: 0x242f - <unknown>!~lib/as-wasi/as-wasi/wasi_abort
         21387: 0x1044 - <unknown>!~lib/rt/itcms/visitRoots
         21388: 0x1970 - <unknown>!~lib/rt/itcms/step
         21389: 0x1a4c - <unknown>!~lib/rt/itcms/interrupt
         21390: 0x1fda - <unknown>!~lib/rt/itcms/__new
         21391: 0x2564 - <unknown>!~lib/string/String#concat
         21392:  0xcd0 - <unknown>!~lib/string/String.__concat
```

**Additional information**

`wasmtime run ./build/untouched.wasm` works fine without crashing.  (If I add some top level statements and `wasmtime run` then these are executed correctly.)  It's only when I pass the `--invoke` option that things go wrong.

The same problem occurs if I embed `wasmtime` and call its API to invoke a function other than `_start`.

The same problem occurs if I use `./build/optimized.wasm`, or the `.wat` build output.

The problem does not occur with AssemblyScript 0.17.2/as-wasi 0.4.3.  With these versions `wasmtime run --invoke foo` runs correctly.

Please let me know if you need any more info - thanks!

### PR DESCRIPTION
**Pull request by dcodeIO**
### ECMAScript modules

Fixes #1306. Migrating our dependencies to ESM made it possible to migrate the compiler and frontend as well, alongside internal utility and scripts. This is a breaking change for consumers of the compiler API (i.e. transforms), but not for command line usage. Viable strategies to account for the changes are:

1. Migrate any code utilizing compiler APIs to ESM as well:

   ```ts
   import assemblyscript from "assemblyscript";
   ...
   ```

2. Utilize a dynamic import while consuming code remains in its current module format:

   ```ts
   const assemblyscript = (await import("assemblyscript")).default;
   ...
   // or
   import("assemblyscript").then(({ default: assemblyscript }) => { ... });
   ```

### Running the compiler on the Web with ESM

Prior, we provided a browser SDK that made use of the AMD module format to load the components necessary to run the compiler on the Web. With the switch to ESM, it is not necessary anymore to provide a separate SDK, but native browser functionality can now be used to utilize the compiler in browsers. To ease the transition, the build system outputs an example `dist/web.html` template with all the right versions in `<script ...>` tags. Alongside, it also sets up `es-module-shims` for import maps support as is currently necessary to support browsers other than those based on Chromium. General outline is:

```html
<script async src="url/to/es-module-shims"></script>
<script type="importmap">
{
  "imports": {
    "binaryen": "url/to/binaryen",
    "long": "url/to/long",
    "assemblyscript": "url/to/assemblyscript"
  }
}
</script>
<script type="module">
import asc from "url/to/asc";
...
</script>
```

### Asynchronous compiler APIs

Prior, programmatically executing for example `asc.main` was synchronous despite accepting a callback. The relevant APIs are now asynchronous, making use of the opportunity to perform asynchronous I/O under the hood, and as such return a promise with the compilation result instead of accepting a callback.

```ts
const { error, stdout, stderr } = await asc.main([ ... ], { ... });
...
```

It is no longer necessary to override `stdout` and `stderr`, since the default has been switched to return a memory stream. If binding to the Node.js console is desired, which is rare, the behavior can be overridden to the previous by specifying `{ stdout: process.stdout, stderr: process.stderr }` in API options.

In addition, transform hooks gained the ability to evaluate asynchronously when being `async` / returning a promise.

### Unification of `===` and `==`

Fixes #856. Closes #1111. The semantics of `===` and `!==` are redundant in AssemblyScript since comparing two values of different types is not permitted anyhow. In the early days of the compiler we hence repurposed the operator to perform what seemed like a useful operation, that is test for identity equality (the exact same object). Doing so, however, introduced a subtle footgun into the language for those coming from TypeScript, and now has been removed.

Means: `===` is now the same as `==`, `!==` is now the same as `!=`, largely matching intuition.

### Deprecation of the loader

The loader was a stopgap solution intended to keep glue code minimal until WebAssembly integrates natively with the rest of the Web platform. Sadly, we made a bet there that didn't materialize, and the loader has now been deprecated with the compiler now supporting static generation of glue code with the `--bindings` option.

Available bindings are:

```
  --bindings, -b        Specifies the bindings to generate (.js + .d.ts).

                          esm  JavaScript bindings & typings with ESM integration.
                          raw  Like esm, but exports just the instantiate function.
                               Useful where modules are meant to be instantiated
                               multiple times or non-ESM imports must be provided.
```

Generated JavaScript bindings support the data types

Type            | Strategy     | Description
-------------|--------------|---------------
Number      | By value      | Basic types except 64-bit integers
BigInt          | By value      | 64-bit integers via js-bigint-integration
String          | Copy           |
ArrayBuffer | Copy           |
TypedArray | Copy           | Any kind
Array           | Copy           | Any kind
StaticArray  | Copy           | Any kind
Object         | Copy           | Plain objects (no constructor or non-public fields).<br />Can opt-out by providing an empty constructor.
Internref      | By value      | Reference counted pointer via FinalizationRegistry.<br />Essentially anything that isn't a plain object.
Externref     | By value      | Via reference-types

For now, only top-level functions, globals and enums receive bindings. Classes do not (yet). Bindings automagically utilize exported runtime helpers so users don't have to.

### Preserving side-effects in static type checks

Fixes #531. The static type checks `isInteger`, `isFloat`, `isBoolean`, `isSigned`, `isReference`, `isString`, `isArray`, `isArrayLike`, `isFunction`, `isNullable`, `isConstant`, `isManaged`, `isVoid`, `lengthof`, `nameof` and `idof` accept either a type argument, an argument or both. In the uncommon case of providing an argument, that is not solely operating on a type, these builtins now preserve side-effects of the argument which is safer but may prevent compile-time branch elimination in such cases.

### Unified consumption of the `assemblyscript` package

Entrypoints for the various components are now:

* `assemblyscript` as before
* `assemblyscript/asc` to obtain the compiler frontend
* `assemblyscript/transform` to obtain the transform base class
* `assemblyscript/binaryen` to obtain the exact instance of Binaryen used
* `assemblyscript/util/*.js` to obtain various utility, i.e. for configuration parsing

### Removal of `ascMain` in `package.json`

Fixes #1954. As it turned out, specifying an alternative entry point in `package.json` led to more issues than it solved, often not finding files and types because existing tooling does not recognize it. As such, this mechanism has been removed in favor of plain node-style resolution, i.e. `import { x } from "myPackage/assembly"`, which is not susceptible to these problems.

### Removal of experimental `--extension` CLI option

See #1003. While it is likely that discussion about using another file extension will continue in the future, the CLI option was meant for experimentation, had various issues and lately became stale. Hence it has been removed to simplify matters on common ground.

### Replaced `--explicitStart` CLI option with `--exportStart NAME`

Fixes #2099. The new option is more general in that it also accepts the desired export name to use for the start function. Typical options are:

* `--exportStart _start` for a WASI command. This is equivalent to the former `--explicitStart`.
* `--exportStart _initialize` for a WASI reactor.
* `--exportStart myCustomStartFunctionName` for anything else.

Note that the start function, no matter how it is named, must always be called before any other exports to initialize the module.

### Renamed untouched/optimized to debug/release

Default compilation targets (generated) for projects are now named debug and release to better fit their purpose and to have only one set of names to remember.

### Enabled various WebAssembly features

Some meanwhile standardized features have been enabled by default:

* **Nontrapping float to int conversions** brings additional conversion operations.
* **Bulk Memory** replaces fallback implementations of `memory.fill` and `memory.copy`.

Note that we are still holding back on enabling SIMD by default as it is not yet supported in Safari, but one can already play with it using `--enable simd`.

### Reworked development workflow

Prior, AssemblyScript utilized `ts-node` in development to lessen overhead from recompilation on changes. This approach turned out to be not viable anymore due to various issues with modern language features and has been dropped, alongside `webpack` for final builds, and replaced with `esbuild`. The new development workflow is to execute `npm run watch` which will automatically and quickly produce builds. As a side effect, workarounds and dependencies to support the prior development workflow could be dropped.

### And the kitchen sink

* Various clean ups have been performed, with no longer needed files and long deprecated APIs being removed
* Support for older Node.js versions not supporting ECMAScript modules has been dropped
* The WebIDL and Asm.js targets have been dropped as they were of little use and largely unmaintained
* The `--listFiles` (not Wasm-target compatible) and `--traceResolution` (now tested programmatically) CLI options have been removed.
* The Binaryen dependency now uses Wasm builds and has been significantly sped up by enabling more optimizations. Optimizing the AssemblyScript compiler itself now only takes about a third of the time.

- [x] I've read the contributing guidelines
- [x] I've added my name and email to the NOTICE file

### CODE REVIEW

File: cli/util/utf8.js [hunk 1]
```diff
@@ -42,38 +33,37 @@ utf8.length = function utf8_length(string) {
...
+    } else if (t > 239 && t < 365) {
       t = ((t & 7) << 18 | (buffer[start++] & 63) << 12 | (buffer[start++] & 63) << 6 | buffer[start++] & 63) - 0x10000;
       chunk[i++] = 0xD800 + (t >> 10);
       chunk[i++] = 0xDC00 + (t & 1023);
-    } else
+    } else {
       chunk[i++] = (t & 15) << 12 | (buffer[start++] & 63) << 6 | buffer[start++] & 63;
-    if (i > 8191) {
+    }
+    if (i >= 8192) {
```
Comment (MaxGraey) [inline cli/util/utf8.js:56]:
```suggestion
    if (i >= 0x2000) {
```

**Comment by MaxGraey** [comment]
> What do to on the Web? We'd need import maps, but these aren't supported universally yet.

How about apply them in AOT style with esbuild-plugin-import-map plugin?
https://github.com/trygve-lie/esbuild-plugin-import-map

**Comment by dcodeIO** [comment]
When the dist files are transformed, these will no longer work under node. Would be cool if we could have universal builds.

**Comment by MaxGraey** [comment]
> When the dist files are transformed, these will no longer work under node. Would be cool if we could have universal builds.

I don't think it's possible now. FF and Safari still den't support import-maps. So either abandon import-maps completely or have two builds. One for node.js and Chrome with import-maps and one without it for everyone else

**Comment by dcodeIO** [comment]
There is [es-module-shims](https://github.com/guybedford/es-module-shims) but I'm not sure if it needs to parse the dist files. That would probably be slow for multi-MB artifacts.

**Comment by MaxGraey** [comment]
Hmm: https://github.com/guybedford/es-module-shims/issues/1#issuecomment-663665852

File: cli/util/utf8.js (hunk 1 above)
Comment (dcodeIO) [reply cli/util/utf8.js:56]: This is just a size/length, not a value, so would rather leave it as-is.

**Comment by MaxGraey** [comment]
I'm wondering could we also do more async IO now?
For example async spawn:
https://github.com/AssemblyScript/assemblyscript/blob/esm/bin/asc.js#L10

async file reads / writes:
https://github.com/AssemblyScript/assemblyscript/blob/esm/cli/index.js#L1146
https://github.com/AssemblyScript/assemblyscript/blob/esm/cli/index.js#L1175
https://github.com/AssemblyScript/assemblyscript/blob/esm/cli/index.js#L1162
https://github.com/AssemblyScript/assemblyscript/blob/esm/cli/index.js#L307

?

**Comment by dcodeIO** [comment]
Would make sense where tasks are parallelizable, say when reading files, yeah, but then leads to more breaking changes since all code down to where files are read must become async, and potentially return promises. In `bin/asc.js` it probably won't matter.

**Comment by MaxGraey** [comment]
asc.main already async and required callback

**Comment by dcodeIO** [comment]
Regarding async `asc.main`: This so far gets stuff going, but I haven't yet touched all the places where things can become parallel, say for example reading multiple files from the backlog at once. Should be doable from here on, though. New API is:

```ts
const { error, stdout, stderr } = asc.main([ ... ], { ... });
...
```

**Comment by dcodeIO** [comment]
Not sure what's up with the bootstrap tests, work for me locally. Seems like waiting for pending promises can still return earlier than output files are actually accessible?

**Comment by MaxGraey** [comment]
What if create "out" dir ahead of time like: "mkdir out && node bin/asc --config src/asconfig.json --target untouched && node bin/asc ....". Another option is add separate script which launch all this stuff but in node.js script file instead npm scripts

**Comment by MaxGraey** [comment]
It seems write times for bootstrapping is not precise: `I/O Write  :  8132.091 ms  n=3`. While before async it was ~200ms

**Comment by dcodeIO** [comment]
Seems to be an effect of deferring the write operations, so measurement begins but the result is only known later, hmm.

**Comment by MaxGraey** [comment]
Could you update binaryen to latest and update all test fixtures?

**Comment by dcodeIO** [comment]
Should already be done I think

**Comment by dcodeIO** [comment]
I have absolutely no idea how that snap stuff is supposed to work, and can't get the `snapcraft` command to function in either WSL or an Ubuntu VM. Will give this this another try in the wild on their build service, and if I can't get it to work with another few commits I'll probably remove it.

**Comment by MaxGraey** [comment]
Could you update binaryen to v103.0.0-nightly.20211203?

**Comment by dcodeIO** [comment]
Done, had no fixture changes :)

File: bin/asc.js [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+if (!hasSourceMaps || hasCustomArgs) {
+  if (!hasSourceMaps) {
+    nodeArgs.push("--enable-source-maps");
+  }
+  if (hasCustomArgs) {
+    const index = args.indexOf("--");
+    nodeArgs.push(...args.slice(index + 1));
+    args.length = index;
+  }
+  childProcess.spawnSync(
```
Comment (MaxGraey) [inline bin/asc.js:20]: Is it possible use async `childProcess.spawn` here?

File: cli/index.d.ts [hunk 3]
```diff
@@ -188,68 +171,118 @@ export interface APIOptions {
   /** Standard error stream to use. */
   stderr?: OutputStream;
   /** Reads a file from disk (or memory). */
-  readFile?: (filename: string, baseDir: string) => string | null;
+  readFile?: (filename: string, baseDir: string) => string | null | Promise<string | null>;
```
Comment (MaxGraey) [inline cli/index.d.ts:174]:
```suggestion
  readFile?: (filename: string, baseDir: string) => (string | null) | Promise<string | null>;
```

File: cli/index.d.ts [hunk 4]
```diff
@@ -188,68 +171,118 @@ export interface APIOptions {
...
   /** Writes a file to disk (or memory). */
-  writeFile?: (filename: string, contents: Uint8Array, baseDir: string) => void;
+  writeFile?: (filename: string, contents: Uint8Array, baseDir: string) => void | Promise<void>;
   /** Lists all files within a directory. */
-  listFiles?: (dirname: string, baseDir: string) => string[] | null;
+  listFiles?: (dirname: string, baseDir: string) => string[] | null | Promise<string[] | null>;
```
Comment (MaxGraey) [inline cli/index.d.ts:178]:
```suggestion
  listFiles?: (dirname: string, baseDir: string) => (string[] | null) | Promise<string[] | null>;
```

File: cli/index.d.ts [hunk 5]
```diff
@@ -188,68 +171,118 @@ export interface APIOptions {
...
+  readonly stdout: OutputStream;
+
+  /** Error stream used by the compiler. */
+  readonly stderr: OutputStream;
+
+  /** Logs a message to console. */
+  readonly log: typeof console.log;
+
+  /** Reads a file from disk. */
+  readFile(filename: string, baseDir: string): string | null | Promise<string | null>;
```
Comment (MaxGraey) [inline cli/index.d.ts:272]: same here

File: cli/index.js [hunk 6]
```diff
@@ -21,28 +21,71 @@
...
+var __newString = str => str;
+var __getString = ptr => ptr;
+var __pin = ptr => ptr;
+var __unpin = _ => undefined;
+var __collect = _ => undefined;
+
+// Use the AS->Wasm variant as an option (experimental)
+const useWasm = process.argv.includes("--wasm");
+if (useWasm) {
+  let argPos = process.argv.indexOf("--wasm");
```
Comment (MaxGraey) [inline cli/index.js:53]:
```suggestion
let argPos = process.argv.indexOf("--wasm");
const useWasm = argPos > 0;
if (useWasm) {
```

File: cli/index.js [hunk 7]
```diff
@@ -21,28 +21,71 @@
...
+          JSON.stringify(gcProfile)
+        );
+        fs.writeFileSync(
+          `rtrace-gc-profile-${timestamp}.csv`,
+          `time,memory,pause\n${gcProfile.join("\n")}`
+        );
+      }
+    }
+  });
+  let { exports } = await loader.instantiate(await (await fetch(binaryPath)).arrayBuffer(), rtraceInstance.install({ binaryen }));
```
Comment (MaxGraey) [inline cli/index.js:78]:
```suggestion
  const { exports } = await loader.instantiate(await (await fetch(binaryPath)).arrayBuffer(), rtraceInstance.install({ binaryen }));
```

File: bin/asc.js (hunk 2 above)
Comment (dcodeIO) [reply bin/asc.js:20]: Unlike `fs`, there are no promise versions for `child-process` as far as I see it, so there is not much value in switching this I guess.

File: cli/index.js [hunk 8]
```diff
@@ -251,28 +153,36 @@ exports.compileString = (sources, options) => {
...
+  if (typeof sources === "string") sources = { [`input${defaultExtension.ext}`]: sources };
+  var argv = [
+    "--binaryFile", "binary",
+    "--textFile", "text",
+  ];
+  configToArguments(config, argv);
+  const output = {};
+  const result = await main(argv.concat(Object.keys(sources)), {
+    stdout: createMemoryStream(),
+    stderr: createMemoryStream(),
```
Comment (MaxGraey) [inline cli/index.js:170]: It looks like `createMemoryStream()` uses quite often as default values for `stdout` and `stderr`. Could we predefine this as standard steams for `asc.main`?

File: cli/index.js [hunk 9]
```diff
@@ -21,28 +21,71 @@
...
+      }
+    }
+  });
+  let { exports } = await loader.instantiate(await (await fetch(binaryPath)).arrayBuffer(), rtraceInstance.install({ binaryen }));
+  assemblyscript = exports;
+  __newString = assemblyscript.__newString;
+  __getString = assemblyscript.__getString;
+  __pin = assemblyscript.__pin;
+  __unpin = assemblyscript.__unpin;
+  __collect = assemblyscript.__collect;
```
[the remark this answers is not in the document]
Comment (dcodeIO) [reply cli/index.js:84]: This is interpreted as a block statement, only works with a leading `var` or similar

File: bin/asc.js (hunk 2 above)
Comment (MaxGraey) [reply bin/asc.js:20]: I see

File: cli/index.js (hunk 9 above)
[the remark this answers is not in the document]
Comment (MaxGraey) [reply cli/index.js:83]: Sorry, I forgot a parenthesis

File: package.json [hunk 10]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "assemblyscript",
-  "description": "Definitely not a TypeScript to WebAssembly compiler.",
+  "description": "A TypeScript-like language for WebAssembly.",
```
Comment (MaxGraey) [inline package.json:3]: 👍🏻

File: package.json [hunk 11]
```diff
@@ -21,110 +20,76 @@
...
-    "ts-node": "^10.4.0"
+    "binaryen": "103.0.0-nightly.20211203",
+    "long": "^5.2.0"
   },
   "devDependencies": {
     "@types/node": "^16.11.6",
     "@typescript-eslint/eslint-plugin": "^5.4.0",
     "@typescript-eslint/parser": "^5.4.0",
     "diff": "^5.0.0",
+    "esbuild": "^0.14.0",
```
Comment (MaxGraey) [inline package.json:31]: Could you update to v0.14.1?

File: cli/index.js (hunk 8 above)
Comment (dcodeIO) [reply cli/index.js:170]: Becomes a little inconsistent in documentation then, since depending on where the CLI runs, Node or Web, the behavior is different, in that one cannot `toString` `process.stdout`. So specifying this explicitly avoids surprises.

File: package.json (hunk 11 above)
Comment (dcodeIO) [reply package.json:31]: I believe that's already in package-lock, and new installs get it anyway. Is there a command to sync package.json with it somehow so one doesn't need to do this manually each time?

File: cli/index.js (hunk 8 above)
Comment (dcodeIO) [reply cli/index.js:170]: What we could do perhaps is invert this, so that a memory stream is always the default, and one would instead specify `process.stdout`. Effectively, the Node CLI is the only one doing that I think.

Comment (dcodeIO) [reply cli/index.js]: Did that now :)

**Review by MaxGraey — APPROVED** [review]

File: bin/asc.js [hunk 12]
```diff
@@ -0,0 +1,32 @@
...
+
+const hasSourceMaps = nodeArgs.includes("--enable-source-maps");
+const hasCustomArgs = args.includes("--");
+
+if (!hasSourceMaps || hasCustomArgs) {
+  if (!hasSourceMaps) {
+    nodeArgs.push("--enable-source-maps");
+  }
+  if (hasCustomArgs) {
+    const index = args.indexOf("--");
```
Comment (MaxGraey) [inline bin/asc.js:16]: Btw could you simplify this as well and reuse `args.indexOf("--")` for `hasCustomArgs`?

File: bin/asc.js [hunk 13]
```diff
@@ -0,0 +1,31 @@
+#!/usr/bin/env node
+
+import childProcess from "child_process";
+
+const [ nodePath, thisPath, ...args ] = process.argv;
+const nodeArgs = process.execArgv;
+
+const hasSourceMaps = nodeArgs.includes("--enable-source-maps");
+const posCustomArgs = args.indexOf("--");
```
Comment (MaxGraey) [inline bin/asc.js:9]: How about?
```suggestion
const posCustomArgs = args.indexOf("--", 2);
```

**Comment by dcodeIO** [comment]
Figured that snaps probably don't provide good UX anyway and deleted it, since to make the compiler work properly, one needs to access stdlib and whatnot from within the snap, which will likely not work if asc sits in a container. Also can't really provide support for that, so it's probably better this way.

**Comment by MaxGraey** [comment]
How about something like this?
```js
const srcReporter = reportPlugin("src");
const cliReporter = reportPlugin("cli");

await Promise.all([
  esbuild.build({ tsconfig: "./src/tsconfig.json", .... }),
  esbuild.build({ entryPoints: [ "./cli/index.js" ], .... })
]);
```
instead `defer` workaround?

**Comment by MaxGraey** [comment]
Did you try add incremental mode for watch script?
https://esbuild.github.io/api/#incremental

**Comment by dcodeIO** [comment]
Last commits made me wonder how much value there actually is in supporting legacy transforms, given that there are other breaking changes one will most likely encounter anyway. It's easy to support, though, doesn't add a lot of code, but perhaps the potential confusion isn't worth it?

File: cli/README.md [hunk 14]
```diff
@@ -13,41 +13,46 @@ $> asc --help
...
-  });
-});
+import asc from "assemblyscript/asc";
+
+const { error, stdout } = await asc.main([
+  "myModule.ts",
+  "--binaryFile", "myModule.wasm",
+  "--optimize",
+  "--sourceMap",
+  "--measure"
```
Comment (MaxGraey) [inline cli/README.md:26]:
```suggestion
  "--stats"
```

File: cli/index.js [hunk 15]
```diff
@@ -0,0 +1,1308 @@
...
+    return [...new Set(values)];
+  }
+
+  // Set up options
+  var program, runtime;
+  const compilerOptions = __pin(assemblyscript.newOptions());
+  switch (opts.runtime) {
+    case "stub": runtime = 0; break;
+    case "minimal": runtime = 1; break;
+    default: runtime = 2; break;
```
Comment (MaxGraey) [inline cli/index.js:333]:
```suggestion
    /* incremental */
    default: runtime = 2; break;
```

File: cli/index.d.ts [hunk 16]
```diff
@@ -169,16 +152,10 @@ export interface CompilerOptions {
   transform?: string | string[];
   /** Make yourself sad for no good reason. */
   pedantic?: boolean;
-  /** Enables tracing of package resolution. */
-  traceResolution?: boolean;
-  /** Lists files to be compiled and exits. */
-  listFiles?: boolean;
   /** Prints measuring information on I/O and compile times. */
   measure?: boolean;
```
Comment (MaxGraey) [inline cli/index.d.ts:156]:
```suggestion
  stats?: boolean;
```

File: tests/allocators/default/package.json [hunk 17]
```diff
@@ -1,5 +1,6 @@
 {
   "private": true,
+  "type": "module",
   "scripts": {
     "build": "npm run build:untouched && npm run build:optimized",
     "build:untouched": "node ../../../bin/asc assembly/index.ts -t untouched.wat -b untouched.wasm --sourceMap --measure --debug",
```
Comment (MaxGraey) [inline tests/allocators/default/package.json:6]:
```suggestion
    "build:untouched": "node ../../../bin/asc assembly/index.ts -t untouched.wat -b untouched.wasm --sourceMap --stats --debug",
```

**Comment by MaxGraey** [comment]
Could you add `stats: true` to `asconfig.json`?

File: cli/options.json [hunk 18]
```diff
@@ -222,6 +219,9 @@
       "",
       " mutable-globals     Mutable global imports and exports.",
       " sign-extension      Sign-extension operations",
+      " nontrapping-f2i     Non-trapping float to integer ops.",
+      " bulk-memory         Bulk memory operations.",
+      " simd                SIMD types and operations.",
```
Comment (MaxGraey) [inline cli/options.json:224]: It's too early. SIMD doesn't support on Safari. Bulk memory generate suboptimal code on binaryen yet. Also has suboptimal performance: https://bugs.chromium.org/p/v8/issues/detail?id=11775&q=maxgraey&can=2

`nontrapping-f2i` I enabled here: https://github.com/AssemblyScript/assemblyscript/pull/2107

Comment (dcodeIO) [reply cli/options.json:224]: Also not 100% sure about SIMD given Safari, but seems ok-ish given that it is standardized and not used by most projects anyhow. Regarding Bulk Memory, we are only using that for memset/memmove currently - how would it lead to problems?

Comment (dcodeIO) [reply cli/options.json:224]: Regarding #2107, let's rebase the specific implementation tweaks on this branch :)

Comment (MaxGraey) [reply cli/options.json:224]: > but seems ok-ish given that it is standardized and not used by most projects anyhow.

SIMD uses during bulk memory lowering for constant size equal `8`. Also I would like add some fast simd path in std. Also note SIMD banned in smart contracts (even integer ops)

Comment (MaxGraey) [reply cli/options.json:224]: > Regarding Bulk Memory, we are only using that for memset/memmove currently - how would it lead to problems?

It increase size and reduce performance in some trivial cases like `memory.fill(p, 0, 3)` or `memory.fill(p, 0, 0)`. Before enabling it better merge some PRs in binaryen and wait better codegen on v8

Comment (dcodeIO) [reply cli/options.json:224]: Wondering, are the Bulk Memory issues perhaps related to lowering it, and not so much to when it is enabled?

Comment (MaxGraey) [reply cli/options.json:224]: > Regarding #2107, let's rebase the specific implementation tweaks on this branch :)

I would like keep that PR separate if you don't mind. This will be easier to find and easier to undo if something goes wrong. I suggest just merge that PR immediate after this PR

Comment (MaxGraey) [reply cli/options.json:224]: > How would the picture change when enabling Bulk Memory but not SIMD?

I suggest you consider including bulk memory later. With a preliminary study of the pros and cons.

Comment (dcodeIO) [reply cli/options.json:224]: I am considering Bulk Memory for its significant code size advantages. We can talk about SIMD, but so far I am not seeing a good reason for not enabling BM.

Comment (MaxGraey) [reply cli/options.json:224]: > I am considering Bulk Memory for its significant code size advantages. We can talk about SIMD, but so far I am not seeing a good reason for not enabling BM.

The problem is that for trivial cases the code slows down. That is, it becomes more expensive to create classes and small objects. I'm not sure yet that bulk memory is ready to be enabled by default. Tests are needed

Comment (dcodeIO) [reply cli/options.json:224]: Testing with the compiler I am seeing a fluctuating 3-4% difference or so, typically in `parse` stage. Hard to tell if that's merely noise, comes from the instruction itself or from what Binaryen does or does not do. In general I think that we should enable new features and improve upon them incrementally, which also has a higher chance to happen once it's out in the wild.

Comment (dcodeIO) [reply cli/options.json]: I now saw in the fixtures however that Bulk Memory is lowed to SIMD, as you said, so I've put SIMD behind a flag again.

File: tests/compiler/function-call.optimized.wat [hunk 19]
```diff
@@ -1257,6 +1257,11 @@
   local.get $0
   i32.const 20
   i32.add
+  local.tee $0
+  i32.const 0
+  i32.const 0
+  memory.fill
```
Comment (dcodeIO) [inline tests/compiler/function-call.optimized.wat:1263]: This is an optimization artifact found in test cases where classes with zero fields are used. Inlines `size=0`, then preserving side effects I suppose, while previously the polyfill could be eliminated. Likely not worth worrying about.

Comment (MaxGraey) [reply tests/compiler/function-call.optimized.wat:1263]: See this PR: https://github.com/WebAssembly/binaryen/pull/4295

**Comment by lalop** [comment]
I want to add a webassembly editor on a web page build with webpack, can I use this branch ?

File: package.json [hunk 20]
```diff
@@ -21,110 +20,77 @@
...
-    "ts-node": "^10.4.0",
-    "typescript": "~4.5.2",
-    "webpack": "^5.64.1",
-    "webpack-cli": "^4.9.1"
+    "typescript": "~4.5.2"
   },
-  "type": "commonjs",
-  "main": "index.js",
-  "types": "index.d.ts",
+  "type": "module",
```
Comment (trusktr) [inline package.json:36]: 🥳

File: bin/asc.js [hunk 21]
```diff
@@ -0,0 +1,33 @@
...
+const isDeno = typeof Deno !== "undefined";
+
+if (isDeno) {
+  process.on = function() { /* suppress 'not implemented' message */ };
+}
+
+if ((!hasSourceMaps || ~posCustomArgs) && !isDeno) {
```
Comment (trusktr) [inline bin/asc.js:14]: What does `pos` stand for?

File: bin/asc.js [hunk 22]
```diff
@@ -0,0 +1,33 @@
...
+  if (!hasSourceMaps) {
+    nodeArgs.push("--enable-source-maps");
+  }
```
Comment (trusktr) [inline bin/asc.js:17]: why support the option if it is always enabled?

Comment (trusktr) [reply bin/asc.js:17]: Oh, I see, it's not AS-specific, we just always want Node to have it enabled.

File: lib/loader/README.md [hunk 23]
```diff
@@ -1,5 +1,318 @@
 # AssemblyScript Loader
 
-A convenient loader for [AssemblyScript](https://assemblyscript.org) modules. Demangles module exports to a friendly object structure compatible with TypeScript definitions and provides useful utility to read/write data from/to memory.
+A tiny module loader that makes working with AssemblyScript modules as convenient as it gets without sacrificing efficiency. It about mirrors the relevant parts of the WebAssembly API while also providing utility to allocate and read strings, arrays and classes.
 
-[Documentation](https://assemblyscript.org/loader.html)
+**DEPRECATION NOTICE:** The loader has been deprecated in AssemblyScript 0.20. It will likely continue to work for a while, but it is recommended to switch to the new static bindings generation.
+
```
Comment (trusktr) [inline lib/loader/README.md:6]: This needs a link to the guide on static bindings.

File: lib/loader/tests/index.js [hunk 24]
```diff
@@ -23,7 +23,9 @@ function test(file) {
 
   // should export memory
   assert(exports.memory instanceof WebAssembly.Memory);
-  assert(typeof exports.memory.compare === "function");
+
+  // NOTE: Namespace exports have been removed in 0.20
+  // assert(typeof exports.memory.compare === "function");
```
Comment (trusktr) [inline lib/loader/tests/index.js:28]: yay, obliterate namespace

File: src/bindings/tsd.ts [hunk 25]
```diff
@@ -0,0 +1,387 @@
...
+    return sb.join("");
+  }
+}
+
+// Helpers
+
+enum Mode {
+  IMPORT,
+  EXPORT
+}
```
Comment (trusktr) [inline src/bindings/tsd.ts:387]: Is there a more readable way to do this, perhaps as template strings instead of concatenating?

File: src/index-wasm.ts [hunk 26]
```diff
@@ -0,0 +1,351 @@
...
+ * @fileoverview The C-like and re-exported public compiler interface.
+ *
+ * The intended way to consume the compiler sources is to import this
+ * file, which again exports all relevant functions, classes and constants
+ * as a flat namespace.
+ *
+ * Note though that the compiler sources are written in "portable
+ * AssemblyScript" that can be compiled to both JavaScript with tsc and
+ * to WebAssembly with asc, and as such require additional glue code
+ * depending on the target.
```
Comment (trusktr) [inline src/index-wasm.ts:11]: so cool

File: std/assembly/bindings/dom.ts [hunk 27]
```diff
@@ -0,0 +1,162 @@
...
+  @external("env", "Reflect.setWithReceiver")
+  @external.js("return Reflect.set(target, propertyKey, value, receiver);")
+  export function setWithReceiver(target: externref, propertyKey: string, value: externref , receiver: externref): externref;
+  @external("env", "Reflect.apply")
+  export function apply(target: externref, thisArgument: externref, argumentsList: externref): externref;
+}
+
+export declare namespace String {
+  @external("env", "String.fromCodePoint")
+  export function fromCodePoint(codepoint: i32): externref;
```
Comment (trusktr) [inline std/assembly/bindings/dom.ts:112]: So if we call this in AS, we get back an `externref`. How will it be useful?

File: std/assembly/bindings/dom.ts [hunk 28]
```diff
@@ -0,0 +1,162 @@
...
+  export function time(label: string): void;
+  @external("env", "console.timeLog")
+  export function timeLog(label: string): void;
+  @external("env", "console.timeEnd")
+  export function timeEnd(label: string): void;
+}
+
+export declare namespace document {
+  @external("env", "document.getElementById")
+  export function getElementById(id: string): externref;
```
Comment (trusktr) [inline std/assembly/bindings/dom.ts:146]: Is the assumption that a library like `asdom` would import these namespaces, then export the ones with the actual types? f.e. `function getElementById(id: string): Element | null`, without `externref`, using wrappers around `externref`?

File: bin/asc.js (hunk 2 above)
Comment (trusktr) [reply bin/asc.js]: Looky looky, Node has a built in function to promisify any callback API:

https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original

Also, it's easy to do manually.

```ts
// take any Node API
declare function anyNodeCallbackAPI(...args, callback) {}

await new Promise((resolve, reject) => {
  anyNodeCallbackAPI(...args, (err, result) => {
    if (err) return reject(err)
    resolve(result)
  })
})
```

That's basically all promisify does.

File: bin/asc.js (hunk 21 above)
Comment (trusktr) [reply bin/asc.js:14]: Oh, piece of poo

**Comment by trusktr** [comment]
> I want to add a webassembly editor on a web page build with webpack, can I use this branch ?

@lalop Yeah, I think so, and probably recommended since the other stuff is becoming obsolete after this huge PR.

**Comment by trusktr** [comment]
@dcodeIO How ready is this to merge? Is it usable enough, such that any further work can be done in new PRs?

File: bin/asc.js (hunk 21 above)
Comment (dcodeIO) [reply bin/asc.js:14]: Stands for position here. Would you like it to be changed?

File: bin/asc.js (hunk 22 above)
Comment (dcodeIO) [reply bin/asc.js:17]: Right, previously was using an npm package for source map support, but recent Node has this option which works better. In particular, when crashing, this produces a proper trace instead of a lot of gibberish.

File: std/assembly/bindings/dom.ts (hunk 27 above)
Comment (dcodeIO) [reply std/assembly/bindings/dom.ts:112]: So far the bindings generate one half of the story, that is translating from AS -> JS. The other half, based on reference types, would be a follow-up PR. I could imagine that it would look like `declare`d classes, to annotate the capabilities of external objects. Something like

```ts
declare class JSString {
  toString(): JSString;
  ...
}
```

then "backed" by `externref`, with the bindings then switching from `externref` to `JSString` and so on. But that's still TODO and tied to eventual table allocation etc.

File: std/assembly/bindings/dom.ts (hunk 28 above)
Comment (dcodeIO) [reply std/assembly/bindings/dom.ts:146]: This is merely what's possible today, since we cannot yet "describe" DOM capabilities purely in AS code, which is still TODO. See also the previous comment on how this could look in the future :)

File: lib/loader/tests/index.js (hunk 24 above)
Comment (dcodeIO) [reply lib/loader/tests/index.js:28]: It's still an open question to me to what extent we'd want to support more complex exports. In particular, I could imagine that when a `class` is exported, and it is used as, say, the return type of an exported function, that a wrapper would be nice. Right now, the two options are either to a) copy field by field to a JS object or b) pass an internal reference. The latter could be extended with a wrapper, but while it would function like a normal object, would have some hidden cost depending on the situation. Right now I'm leaning to leaving this TBD and tackle once use cases arise.

File: src/bindings/tsd.ts (hunk 25 above)
Comment (dcodeIO) [reply src/bindings/tsd.ts:387]: I assume you refer to the whole file? If so, both the .js and .d.ts generation utilize a mix as I saw fit. In particular it uses `.push`es where there are branches in between, and there are a lot. Looks a bit overloaded, I'd agree.
