### PR TITLE
fix: Fix wrong string comparision when sizes are differ

### LINKED ISSUE #1582: [ BUG ] String compare broken on sub-strings
[Here is an example](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1ub25lJnJ1bnRpbWU9bm9uZQovKiogQ2FsY3VsYXRlcyB0aGUgbi10aCBGaWJvbmFjY2kgbnVtYmVyLiAqLwpleHBvcnQgZnVuY3Rpb24gZmliKG46IGkzMik6IGkzMiB7CiAgbGV0IG9uZSA9ICIxIjsKICBsZXQgdGVuID0gIjEwIjsKICByZXR1cm4gb25lIDwgdGVuIHx8IG9uZSA+IHRlbiB8fCBvbmUgPT0gdGVuOwp9CiMhaHRtbAo8dGV4dGFyZWEgaWQ9Im91dHB1dCIgc3R5bGU9ImhlaWdodDogMTAwJTsgd2lkdGg6IDEwMCUiIHJlYWRvbmx5PjwvdGV4dGFyZWE+CjxzY3JpcHQ+CmxvYWRlci5pbnN0YW50aWF0ZShtb2R1bGVfd2FzbSwgeyAvKiBpbXBvcnRzICovIH0pCiAgLnRoZW4oKHsgZXhwb3J0cyB9KSA9PiB7CiAgICBjb25zdCBvdXRwdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnb3V0cHV0JykKICAgIGZvciAobGV0IGkgPSAwOyBpIDw9IDEwOyArK2kpIHsKICAgICAgb3V0cHV0LnZhbHVlICs9IGBmaWIoJHtpfSkgPSAke2V4cG9ydHMuZmliKGkpfVxuYAogICAgfQogIH0pCjwvc2NyaXB0Pg==) of comparing the string "1" and "10", and it is never the case that is either less than, greater than, or equal to.  I would expect "1" to be less than "10" :)

### PR DESCRIPTION
**Pull request by MaxGraey**
Fix #1582

- [x] I've read the contributing guidelines

### CODE REVIEW

**Review by dcodeIO — APPROVED** [review]

File: std/assembly/util/sort.ts [hunk 1]
```diff
@@ -32,10 +32,11 @@ export function COMPARATOR<T>(): (a: T, b: T) => i32 {
       if (a === b || a === null || b === null) return 0;
       var alen = changetype<string>(a).length;
       var blen = changetype<string>(b).length;
-      if (!alen && !blen) return 0;
+      if ((alen | blen) == 0) return 0;
```
Comment (dcodeIO) [inline std/assembly/util/sort.ts:35]: Minor suggestion for patterns like these:
```suggestion
      if (!(alen | blen)) return 0;
```
A little more compact to parse, and unary `i32.eqz` with no constant right away so a little lighter to optimize. Probably not super important, more a case of "why not" when there is the opportunity :)

File: std/assembly/util/sort.ts [hunk 2]
```diff
@@ -32,10 +32,11 @@ export function COMPARATOR<T>(): (a: T, b: T) => i32 {
...
       if (!alen) return -1;
       if (!blen) return  1;
-      return compareImpl(changetype<string>(a), 0, changetype<string>(b), 0, <usize>min(alen, blen));
+      let res = compareImpl(changetype<string>(a), 0, changetype<string>(b), 0, <usize>min(alen, blen));
+      return res == 0 ? alen - blen : res;
```
Comment (dcodeIO) [inline std/assembly/util/sort.ts:39]: This is a little less clear than before, but also avoids a bit of parsing and optimizing work. An `if` on a `local.get` instead of a `i32.eq` with a constant.

```suggestion
      return res ? res : alen - blen;
```

Again, a minor nit. Not yet sure how much we should focus on these things considering that stdlib parses with every and compiles with many programs. Hmm...
