### PR TITLE
Fix invalid codegen on small to long int cast

### LINKED ISSUE #1911: wasm-validator error: i64 != i32: binary child types must be equal
```
  [TestFile.ts] ..\..\node_modules\@as-pect\assembly\assembly\index.ts --runtime stub --debug --binaryFile output.wasm --explicitStart --use ASC_RTRACE=1 --exportTable --importMemory --transform D:\code\serde-as\node_modules\@as-pect\core\lib\transform\index.js

[wasm-validator error in function start:assembly/__tests__/compactInt.spec~anonymous|0~anonymous|0] i64 != i32: binary child types must be equal, on
(i32.and
 (i64.extend_i32_u
  (i32.load16_u
   (local.get $15)
  )
 )
 (i32.const 65535)
)
[wasm-validator error in function start:assembly/__tests__/compactInt.spec~anonymous|0~anonymous|0] i64 != i32: i32 op, on
(i32.and
 (i64.extend_i32_u
  (i32.load16_u
   (local.get $15)
  )
 )
 (i32.const 65535)
)
[Error] There was a compilation error when trying to create the wasm binary for file: assembly/__tests__/compactInt.spec.ts.
Error: validate error
    at Object.main (D:\code\serde-as\node_modules\assemblyscript\cli\asc.js:876:23)
    at D:\code\serde-as\node_modules\@as-pect\cli\src\run.ts:633:11
    at Array.forEach (<anonymous>)
    at run (D:\code\serde-as\node_modules\@as-pect\cli\src\run.ts:630:32)
    at Object.asp (D:\code\serde-as\node_modules\@as-pect\cli\src\index.ts:61:5)
    at Object.<anonymous> (D:\code\serde-as\node_modules\@as-pect\cli\src\test.ts:1:28)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### PR DESCRIPTION
**Pull request by dcodeIO**
fixes #1911

- [x] I've read the contributing guidelines

### CODE REVIEW

File: src/flow.ts [hunk 1]
```diff
@@ -1351,6 +1351,13 @@ export class Flow {
           case UnaryOp.ClzI32:
           case UnaryOp.CtzI32:
           case UnaryOp.PopcntI32: return type.size < 7;
+
+          // sign extensions overflow if result can have high garbage bits in the target type
+          case UnaryOp.Extend8I32: return type.size < (type.isUnsignedIntegerValue ? 32 : 8);
+          case UnaryOp.Extend8I64: return type.size < (type.isUnsignedIntegerValue ? 64 : 8);
+          case UnaryOp.Extend16I32: return type.size < (type.isUnsignedIntegerValue ? 32 : 16);
+          case UnaryOp.Extend16I64: return type.size < (type.isUnsignedIntegerValue ? 64 : 16);
+          case UnaryOp.Extend32I64: return type.size < (type.isUnsignedIntegerValue ? 64 : 32);
```
Comment (dcodeIO) [inline src/flow.ts:1360]: Perhaps a comment here for review, by example of `i32.extend16_s`:

If the target type is unsigned, an `i32.extend16_s` can yield high garbage bits if the target type is smaller than `u32`, which naturally does not care about garbage bits.

If the target type is signed, an `i32.extend16_s` can yield high garbage bits if the target type is smaller than `i16`. Otherwise it would set all high bits to either 0 or 1, which is valid.

**Review by MaxGraey — APPROVED** [review]
