### PR TITLE
fix: Expression passed to `evaluateCondition` asserted to be valid

### LINKED ISSUE #1990: Compiler crash for instance properties without this
This code just crash whole compiler:

```ts
class ArrayIterator {
  constructor(public start: i32, public end: i32) {}

  next(): i32 {
    let start = this.start + 1;
    if (start <= end) { // This line caused crash (just missing this.end)
      this.start = start;
      return start;
    }
    return -1;
  }
}

export function iter1(n: i32): i32 {
  let iter = new ArrayIterator(0, n);
  let acc = 0, val = 0;
  while ((val = iter.next()) != -1) {
    acc++;
  }
  return acc;
}
```

### PR DESCRIPTION
**Pull request by romdotdog**
`getExpressionType` can return Unreachable type if expression passed is invalid
fixes #1990 

- [x] I've read the contributing guidelines
- [x] I've added my name and email to the NOTICE file

### CODE REVIEW

**Review by MaxGraey — APPROVED** [review]

File: src/compiler.ts [hunk 1]
```diff
@@ -10067,7 +10067,11 @@ export class Compiler extends DiagnosticEmitter {
 
   /** Evaluates a boolean condition, determining whether it is TRUE, FALSE or UNKNOWN. */
   evaluateCondition(expr: ExpressionRef): ConditionKind {
-    assert(getExpressionType(expr) == TypeRef.I32);
+    let type = getExpressionType(expr);
+    if (type == TypeRef.Unreachable)
+      return ConditionKind.UNKNOWN; // invalid expression given
```
Comment (dcodeIO) [inline src/compiler.ts:10072]: Not necessarily an "invalid" expression, but one that never returns (result is unreachable) according to Binaryen internals. The fix looks good, but I think the comment can be removed.

**Review by dcodeIO — APPROVED** [review]

**Comment by MaxGraey** [comment]
Thanks!
